ARG        ELIXIR="1.17.3"
ARG           OTP="27.1.1"
ARG        DEBIAN="buster-20240612-slim"
ARG DEVELOP_IMAGE="hexpm/elixir:${ELIXIR}-erlang-${OTP}-debian-${DEBIAN}"
# ------------------------------------------------------------------------------
FROM ${DEVELOP_IMAGE} AS develop
# ------------------------------------------------------------------------------

# install build dependencies
RUN apt-get update -y && \
    apt-get install -y build-essential git inotify-tools && \
    apt-get clean && \
    rm -f /var/lib/apt/lists/*_*

# prepare build dir
WORKDIR /app

# install hex + rebar and Phoenix
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex phx_new --force

# Copies and makes excecutable the script to start the service.
COPY entrypoint.sh ./
RUN chmod +x entrypoint.sh
RUN sed -i -e 's/\r$//' entrypoint.sh
# ERROR: If any of these shell scripts are saved with Windows ('\r\n' endlines)
# will throw the following error:
#   exec ./script.sh: no such file or directory
# SOLUTION: RUN sed -i -e 's/\r$//'

COPY contexts ./

# Copies the script to generate Auth0 context files.
RUN chmod +x auth0.sh
RUN sed -i -e 's/\r$//' auth0.sh

# Copies the script to generate Auth0 context files.
RUN chmod +x open_ai.sh
RUN sed -i -e 's/\r$//' open_ai.sh

CMD ["./entrypoint.sh"]