# Available versions: https://hub.docker.com/r/hexpm/elixir/tags
ARG ELIXIR=1.16.2
ARG OTP=26.2.3
ARG DEBIAN=bullseye-20240130-slim
ARG DEVELOP_IMAGE="hexpm/elixir:${ELIXIR}-erlang-${OTP}-debian-${DEBIAN}"

FROM ${DEVELOP_IMAGE} as develop

# install build dependencies
RUN apt-get update -y && \
    apt-get install -y build-essential git inotify-tools && \
    apt-get clean && \
    rm -f /var/lib/apt/lists/*_*

# prepare build dir
WORKDIR /app

# install hex + rebar and Phoenix
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex phx_new --force

# Copies and makes excecutable the script to start the service.
COPY run.sh ./
RUN chmod +x run.sh
CMD ./run.sh