services:
  app:
    container_name: Application
    build:
      dockerfile: ./Dockerfile.dev
    # environment:
    ports:
      - $HOST_PORT:$INTERNAL_PORT
    volumes:
      - ./src:/app/src
    links:
      - database
    depends_on: 
      database:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:4000 || exit 1
      timeout: 45s
      interval: 10s
      retries: 10

  database:
    container_name: Database
    hostname: database
    image: postgres:14
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: pg_isready -q -d postgres -U postgres
      timeout: 45s
      interval: 10s
      retries: 10
