# Available versions: https://hub.docker.com/r/hexpm/elixir/tags
ARG ELIXIR=1.16.2
ARG OTP=26.2.3
ARG DEBIAN=bullseye-20240130-slim
ARG DEVELOP_IMAGE="hexpm/elixir:${ELIXIR}-erlang-${OTP}-debian-${DEBIAN}"

FROM ${DEVELOP_IMAGE} as develop

# install build dependencies
RUN apt-get update -y && \
    apt-get install -y build-essential git inotify-tools && \
    apt-get clean && \
    rm -f /var/lib/apt/lists/*_*

# prepare build dir
WORKDIR /app

# install hex + rebar and Phoenix
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex phx_new --force

# Copies the script to generate mutation files.
COPY ./schemas.sh ./
# Copies and makes excecutable the script to start the service.
COPY ./.framework/entrypoint.sh ./
RUN chmod +x entrypoint.sh
# If the script is saved with win (\r\n) will throw the following error:
# exec ./entrypoint.sh: no such file or directory
# This line cleans it all.
RUN sed -i -e 's/\r$//' schemas.sh
RUN sed -i -e 's/\r$//' entrypoint.sh

CMD ./entrypoint.sh