services:
  app:
    container_name: back-end
    hostname: lorem-ipsum
    image: lorem-ipsum:0.0.0
    build:
      dockerfile: Dockerfile
    env_file: 
      - ./.env
    environment:
      DATABASE_HOST: database_host
    ports:
      - 4000:4000
    volumes:
      - ./:/app/src
    links:
      - database
    depends_on: 
      database:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:4000 || exit 1
      timeout: 45s
      interval: 10s
      retries: 10

  database:
    container_name: database
    hostname: database_host
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -q -d postgres -U postgres
      timeout: 45s
      interval: 10s
      retries: 10

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pass
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - 5050:5050
    depends_on:
      - database
    volumes:
      - ./priv/repo/pgadmin/servers.json:/pgadmin4/servers.json
      - ./priv/repo/pgadmin/pgpass:/pgadmin4/pgpass
  