defmodule Mix.Tasks.Workbench.Setup do
  use Igniter.Mix.Task

  @example "mix workbench.setup --internal-port 4000 --yes"
  @shortdoc "Makes a freshly generated Phoenix project run in the workbench, nothing else"

  @moduledoc """
  #{@shortdoc}

  It applies only what the dockerized workspace *requires* to boot the
  project, and none of the workbench's opinions. The result is a stock
  `phx.new` project that `./wb.sh up` can run — features are added
  afterwards, one by one, with `./wb.sh add` (the chiefs_setup
  collection inserts the opinionated picks in one go).

  In a single atomic patch set it:

  * binds the dev endpoint to `0.0.0.0` — with the compose pod pattern
    (`network_mode: "service:network"`) the published port arrives on the
    namespace interface, never on loopback, so a server left on
    `127.0.0.1` starts but answers nothing
  * generates `.env` and `.env.sample` — the workspace compose declares
    `env_file: ./.env`, so a missing file aborts `docker compose` before
    boot, and `PORT` / `DATABASE_URL` / `SECRET_KEY_BASE` are what the
    production release reads at runtime. The database line is the one
    the ecto cartridge writes after an insert
    (`WorkbenchIgniter.Features.Ecto.connection/2`): the workspace's
    server for the adapter the project was generated with — Postgres,
    MySQL or MSSQL, with phx.new's own credentials, on `localhost`
    inside the pod — or the path of the SQLite file on its volume
  * adds `.env` to `.gitignore` — that file carries the generated secret

  Everything the retired opinionated setup used to do is deliberately
  absent: the initial version, the base config (ANSI colors,
  `:utc_datetime_usec` generators, migration types, `dev_routes` in
  test), the `README.md`, `CHANGELOG.md` and `.tool-versions`
  templates, and every feature installer (`composes: []`).

  Out of the task's scope in both editions: the dev `Dockerfile.local`,
  copied into the workspace by the workbench script, and the production
  `Dockerfile`/`.dockerignore`, generated by `mix phx.gen.release --docker`.

  ## Example

      #{@example}

  ## Options

  * `--internal-port` - Port the server binds inside the container
    (`PORT` in `.env`); must match the workspace compose mapping.
    Default: `4000`.
  * `--no-ecto` - The project was generated without Ecto: `.env` carries
    no database line.
  """

  @impl Igniter.Mix.Task
  def info(_argv, _composing_task) do
    %Igniter.Mix.Task.Info{
      group: :workbench_igniter,
      example: @example,
      composes: [],
      schema: [
        internal_port: :string,
        ecto: :boolean
      ],
      defaults: [
        internal_port: "4000",
        ecto: true
      ]
    }
  end

  @impl Igniter.Mix.Task
  def igniter(igniter) do
    opts = igniter.args.options
    app_name = Igniter.Project.Application.app_name(igniter)
    web_module = Igniter.Libs.Phoenix.web_module(igniter)
    endpoint = Module.concat(web_module, Endpoint)

    igniter
    |> bind_dev_endpoint(app_name, endpoint)
    |> create_env_files(app_name, opts)
    |> WorkbenchIgniter.IgnoreFile.entry(
      "Secrets required to configure the application.",
      ".env"
    )
  end

  # --- config/dev.exs ---------------------------------------------------------

  defp bind_dev_endpoint(igniter, app_name, endpoint) do
    # Allow access from all machines in the Docker network.
    Igniter.Project.Config.configure(
      igniter,
      "dev.exs",
      app_name,
      [endpoint, :http, :ip],
      {0, 0, 0, 0}
    )
  end

  # --- .env / .env.sample -----------------------------------------------------

  defp create_env_files(igniter, app_name, opts) do
    # The adapter the project was generated with, read off its driver —
    # the same reading the ecto cartridge and the status make.
    {facts, igniter} = WorkbenchIgniter.PhxDelta.facts(igniter)

    # The template's feature sections read their flags through
    # `assigns[...]`, so a vanilla project simply passes none of them.
    env_assigns = [
      app_name: to_string(app_name),
      # PORT is the port the server binds INSIDE the container; the host
      # port only lives in the workspace compose port mapping.
      port: opts[:internal_port],
      ecto: opts[:ecto],
      connection: WorkbenchIgniter.Features.Ecto.connection(facts.database, app_name),
      secret_key_base: WorkbenchIgniter.secret_key_base()
    ]

    # Same template as .env, with the secret blanked out: the sample is
    # meant to be committed, so it must never carry a real secret.
    sample_assigns = Keyword.put(env_assigns, :secret_key_base, "")

    igniter
    |> WorkbenchIgniter.plant_template(
      "env.eex",
      ".env.sample",
      sample_assigns,
      on_exists: :overwrite
    )
    # Secrets are generated once: an existing .env is never overwritten.
    |> WorkbenchIgniter.plant_template(
      "env.eex",
      ".env",
      env_assigns,
      on_exists: :skip
    )
  end
end
