#!/usr/bin/env python3
"""The house's design tokens, projected to whoever consumes them.

    ./assets/design/build.py            write every projection
    ./assets/design/build.py --check    exit 1 if any projection is stale

Reads tokens.json — the one source — and writes, marked as generated:

  generated/tokens.css          custom properties for the console (light on
                                :root, dark under prefers-color-scheme guarded
                                by :root:not([data-theme="light"]), and again
                                under :root[data-theme="dark"])
  generated/components.css      the house's components — the cartridge ref
                                (a mention of a cartridge: state dot, name,
                                always the door to its detail), the door and
                                the probe (an address on the app's port: one
                                you press, one the console calls) and the
                                stamp (the golden state seal) — consumed by
                                the console mock, the LiveView console and
                                the box-back plates
  ../../console/priv/static/favicon.svg
                                the tab's mark: the workbench's own logo.svg
                                in board-ink on a board plate, because a mark
                                drawn in currentColor has no band to take ink
                                from in a tab strip
  generated/diagram-design.md   the diagram-design skill's style guide, with
                                the house's roles and type mapped onto its
                                semantic roles; also installed as the profile
                                ~/.diagram-design/profiles/workbench.md, which
                                the repository's .diagram-design marker names

Run from the repository root.
"""
import json, os, re, sys, datetime, shutil, textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
GEN = os.path.join(HERE, "generated")
CHECK = "--check" in sys.argv
T = json.load(open(os.path.join(HERE, "tokens.json")))
PALETTE = {k: v["value"] for k, v in T["palette"].items()}

def resolve(v):
    return re.sub(r"\{([\w-]+)\}", lambda m: PALETTE[m.group(1)], v)

def role(name, mode):
    r = T["roles"][name]
    return resolve(r["value"] if "value" in r else r[mode])

def hex_to_rgb(h):
    h = h.lstrip("#"); return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))

def rgba(h, a):
    return "rgba(%d,%d,%d,%s)" % (*hex_to_rgb(h), a)

HEADER = "/* generated by assets/design/build.py from assets/design/tokens.json — edit the tokens, not this */\n"

# --- tokens.css ----------------------------------------------------------------
def css_block(mode, indent):
    lines = []
    for name, r in T["roles"].items():
        if "value" in r and mode == "dark":
            continue  # one value, both themes: written once on :root
        lines.append(f"{indent}--{name}:{role(name, mode)};")
    if mode == "light":
        for key, f in T["type"].items():
            lines.append(f'{indent}--{f["css"]}:"{f["family"]}",{f["fallback"]};')
    return "\n".join(lines)

# `color-scheme` rides along in each of the three blocks rather than being
# written once by hand somewhere. It has to switch exactly when the roles
# switch — it is what makes the browser paint its own scrollbars, form
# controls and default grounds in the matching variant — and a hand-written
# copy of this three-state dance would be one more thing to forget the day
# the dance changes.
def tokens_css():
    return (HEADER +
            ":root{\n  color-scheme: light;\n" + css_block("light", "  ") + "\n}\n"
            "@media (prefers-color-scheme: dark){\n  :root:not([data-theme=\"light\"]){\n    color-scheme: dark;\n" + css_block("dark", "    ") + "\n  }\n}\n"
            ":root[data-theme=\"dark\"]{\n  color-scheme: dark;\n" + css_block("dark", "  ") + "\n}\n")

# --- the diagram skill's style guide -------------------------------------------
# The skill thinks in paper/ink/muted/soft/rule/accent/link; the house in
# ground/surface/ink/muted/line/accent. The mapping, with its reasons:
#   paper      <- ground     the page; the diagram sits on it
#   paper-2    <- surface-2  the framed variant's container
#   ink/muted/soft/link/accent <- the same roles
#   rule       <- line       hairlines; the skill's rule is ink at 12%, ours a hex
#   rule-solid <- muted at 45%
#   accent-tint<- accent at 10% (light) / 14% (dark), as accent-soft
#   title      <- text (Source Serif 4): the serif the backs are set in
#   node-name  <- display (Barlow Condensed): the band's lettering
#   sublabel/eyebrow/arrow-label <- code (IBM Plex Mono)
def guide():
    L = lambda n: role(n, "light"); D = lambda n: role(n, "dark")
    disp, text, code = T["type"]["display"]["family"], T["type"]["text"]["family"], T["type"]["code"]["family"]
    fonts = T["google-fonts"]
    return f"""# Style Guide

**The single source of truth for colors, typography, and tokens** of this
install — generated from the workbench's `assets/design/tokens.json` by
`assets/design/build.py`. Edit the tokens there and rebuild; never edit
this file.

The skin is the Dockerized Elixir Workbench's: a violet-tinted ground,
violet-black ink, the gold of the seal as the one accent, the band's
condensed lettering for names and the backs' serif for titles.

---

## Tokens

### Semantic roles

Every token is referred to by **semantic role**, not by its hex value. Type references (`type-*.md`) and SKILL.md say `accent`, not a hex.

| Role | Purpose | Default (light) | Default (dark) |
|---|---|---|---|
| `paper` | Page background, default node fill | `{L("ground")}` | `{D("ground")}` |
| `paper-2` | Diagram container bg, secondary fill | `{L("surface-2")}` | `{D("surface-2")}` |
| `ink` | Primary text, primary stroke | `{L("ink")}` | `{D("ink")}` |
| `muted` | Secondary text, default arrow stroke | `{L("muted")}` | `{D("muted")}` |
| `soft` | Sublabels, boundary labels | `{L("soft")}` | `{D("soft")}` |
| `rule` | Hairline borders | `{L("line")}` | `{D("line")}` |
| `rule-solid` | Stronger borders, baselines | `{rgba(L("muted"), 0.45)}` | `{rgba(D("muted"), 0.45)}` |
| `accent` | Focal / 1–2 max per diagram | `{L("accent")}` | `{D("accent")}` |
| `accent-tint` | Fill for accent-bordered boxes | `{L("accent-soft")}` | `{D("accent-soft")}` |
| `link` | HTTP/API calls, external arrows | `{L("link")}` | `{D("link")}` |

> **Brand palette source:** the workbench's palette — `violet {PALETTE["violet"]}` (the covers' board), `gold {PALETTE["gold"]}` (the seal; `{PALETTE["gold-deep"]}` on light ground), and the violet-tinted greys the console reads on. `board` (`{PALETTE["violet"]}`) is not a diagram role: it is the band and the covers, and a node painted in it would read as a box, not a component.

### Inversion rule (light → dark)

Any `rgba(29,20,36, X)` in light becomes `rgba(239,231,242, X)` in dark. Same opacities, RGB flipped. The accent brightens from the deep gold to the seal's gold on dark paper.

### Series palette (multi-series chart types only)

The workbench's service colours, which its logs already use to tell services apart; `accent` stays reserved for the focal series.

| Token | Light | Dark | Notes |
|---|---|---|---|
| `series-1` | `{role("svc-app","light")}` | `{role("svc-app","light")}` | the app |
| `series-2` | `{role("svc-database","light")}` | `{role("svc-database","light")}` | the database |
| `series-3` | `{role("svc-pgadmin","light")}` | `{role("svc-pgadmin","light")}` | pgAdmin |
| `series-4` | `{role("svc-balancer","light")}` | `{role("svc-balancer","light")}` | the balancer |
| `series-5` | `{role("svc-network","light")}` | `{role("svc-network","light")}` | the network container |

Fills sit at `0.18` opacity light, `0.22` dark; strokes use the full color. **Don't backfill these tokens to non-chart types.**

### Terminal skin (opt-in alternate)

The console's own terminal, for the terminal-window primitive (see [primitive-terminal.md](primitive-terminal.md)).

| Token | Hex | Purpose |
|---|---|---|
| `terminal-page` | `{D("ground")}` | Page background behind the window |
| `terminal-paper` | `{role("term","light")}` | Window body, node fill |
| `terminal-bar` | `{role("term-line","light")}` | Titlebar strip |
| `terminal-border` | `{role("term-line","light")}` | Window border, hairlines |
| `terminal-ink` | `{role("term-ink","light")}` | Primary text, primary stroke |
| `terminal-muted` | `{role("term-dim","light")}` | Secondary text, sublabels, ring stroke |
| `terminal-soft` | `{D("soft")}` | Tertiary — inactive dots, spokes |
| `terminal-accent` | `{D("accent")}` | The one accent — focal station, prompt sign, active dot |
| `terminal-accent-tint` | `{D("accent-soft")}` | Fill for accent-bordered boxes |

**1-accent rule still holds.**

---

## Typography

| Role | Family | Size | Weight | Usage |
|---|---|---|---|---|
| `title` | {text} | 1.75rem | 400 | Page H1 |
| `node-name` | {disp} | 13px | 600, tracked 0.04em | Human-readable labels |
| `sublabel` | {code} | 9px | 400 | Port, protocol, URL, field type |
| `eyebrow` | {code} | 7–8px | 500, tracked 0.18em, uppercase | Type tags, axis labels |
| `arrow-label` | {code} | 8px | 400, tracked 0.06em | Arrow annotations |
| `callout` | {text} *italic* | 14px | 400 | Editorial asides only |

### Font stack

```html
<link href="{fonts}" rel="stylesheet">
```

**Load-bearing rule:** Mono is for *technical* content (ports, commands, URLs, field types). Names go in {disp} — the band's lettering, so a node reads like a label on the machine. Page title is {text}. Italic {text} is reserved for annotation callouts (see [primitive-annotation.md](primitive-annotation.md)). **Never JetBrains Mono** as a blanket "dev" font.

---

## Stroke, radius, spacing

| Token | Value | Use |
|---|---|---|
| `stroke-thin` | `0.8` | Tag-box outlines, leaf nodes |
| `stroke-default` | `1` | Most strokes |
| `stroke-strong` | `1.2` | Emphasis strokes |
| `radius-sm` | `4` | Small tags |
| `radius-md` | `6` | Node boxes |
| `radius-lg` | `8` | Containers, rings |
| `grid` | `4` | Every coord, size, and gap is divisible by 4 (hard rule) |

---

## Node type → treatment

Semantic role combinations — reference these by name in type specs.

| Type | Fill | Stroke |
|---|---|---|
| `focal` (1–2 max) | `accent-tint` | `accent` |
| `backend` | `{L("surface")}` (surface; `{D("surface")}` dark) | `ink` |
| `store` | `ink @ 0.05` | `muted` |
| `external` | `ink @ 0.03` | `ink @ 0.30` |
| `input` | `muted @ 0.10` | `soft` |
| `optional` | `ink @ 0.02` | `ink @ 0.20` dashed `4,3` |
| `security` | `accent @ 0.05` | `accent @ 0.50` dashed `4,4` |

---

## Customizing the skin

This guide is a projection of `assets/design/tokens.json` in the workbench repository: change the tokens and run `./assets/design/build.py`, which rewrites this file and the installed profile.

### Constraints (don't break these)

- **Contrast**: `ink` must hit WCAG AA on `paper`. `muted` must hit AA on `paper` for 11px+ text.
- **One accent**: the seal's gold. Two accents erases the focal signal.
- **No rainbow palette**: the service colours are for series only.
- **Serif + condensed + mono**: three families, not more.
- **Dot pattern is optional, not default.**
- **Container is clean by default.**
"""

def profile(body):
    today = datetime.date.today().isoformat()
    return (f"<!-- diagram-design-profile\nname: {T['name']}\nslug: workbench\nsource-url: none\n"
            f"created: 2026-08-29\nupdated: {today}\nnotes: generated from assets/design/tokens.json by assets/design/build.py\n-->\n" + body)

# --- write or check --------------------------------------------------------------
# --- components.css ------------------------------------------------------------
def components_css():
    return HEADER + """/* The house's components — notation, not layout. Anything that mentions
   a cartridge, anywhere, wears the same reference; the state seal is the
   one golden thing. Both consoles and the box-back plates read these.

   .cart-ref — a mention of a cartridge, always a link to its detail.
     bare     on the shelf, not inserted (hollow dot)
     .in      inserted (good dot)
     .unknown no such cartridge (dashed, struck, no link)
     Never gold: the accent belongs to the stamp. On a printed back
     plate use the state-free bare form — a plate knows no project.
   .door-ref — an address on the app's port that a cartridge opened:
     exdoc's /dev/docs, mailer's /dev/mailbox, ash's /admin. One order
     wherever it is read — the label first, in the house's lettering
     because it is a name, then the address in mono because it is read
     off the machine. Who opened it is not part of it: that is a mention
     of a cartridge, so it goes beside as a .cart-ref and opens that box
     with the same click. The console had this twice with the two halves
     swapped — <small> was the cartridge in the rail and the door's own
     name on the box, so learning one taught the reader the other wrong.
     The addresses the workbench opens itself (app, pgAdmin) wear it too,
     with nothing beside them: having nobody to name is the fact.
     The states are the house's own, not its: pressable while something
     answers, .unlit with the reason in the title when nothing does — the
     app is down, the cartridge is not inserted. An unlit door drops its
     href as well. .unlit cannot stop a link, and by its own rule what
     must not fire is prevented where it is bound.
   .probe-ref — the same address when the console is the one calling it:
     healthcheck2's {path}/live, polled every few seconds. It is the door
     minus the box — no border, no ground, no cursor — which is the line
     already drawn between the chip and the mention, one floor down: a
     bordered box is a door you press, and nobody presses a probe. What
     it answered goes beside it in a .chip (200, no answer), the house's
     word for a reading. The two are declared together here so they can
     never drift into one face again, which is how the mention and the
     chip became the same declaration.
   .chip — a reading the console reports: a container's health, a job's
     exit code, the edition of a box. It is deliberately nothing like the
     mention, which it once was to the declaration: the two say different
     kinds of thing and had grown the same face. Two things separate them
     now. Shape — a bordered box with a dot is a door you press; a chip is
     never pressable, so it has neither. Voice — mono in lower case, which
     in the console already means read off the machine, where the house's
     condensed uppercase means a name. The dot survives on one thing only,
     .busy, where it means something is moving.
     bare    a fact with no state: v0.2.0, base, collection
     .good/.warn/.bad  a state, on a plate tinted from its colour
     .off    an absence — not baked, idle, nothing is up: no plate at all.
             It keeps the plated chips' padding even so. The plate is what
             it drops, not the space: these read in columns beside their
             plated siblings — baked over not baked, running over down —
             and a narrower padding gave the same column two left edges
             depending on the state of the row. What the reader should see
             changing between two rows is the plate and the word, never
             where the word starts.
     .busy   with one of the above: the dot comes back, and pulses
   .unlit — the house's one way of saying not available. The rule it
     carries: never hide what the reader could have. A control they could
     make appear stays where it is, wearing this, with the reason in its
     title and, where there is one, the action that would light it; a tab
     the console can show is part of its map whether or not it can be
     opened today. Hiding is only for what is not applicable and never
     will be here. The console lights up when a cartridge is inserted —
     this is that verb, negated, and it is why the name is not `off`,
     which a chip already uses for something else: a chip reports an
     absence out in the world (not baked, idle), .unlit marks a control
     you cannot use yet. Applies equally to [disabled] and to
     aria-disabled, which is what a tab must use: a disabled <button>
     takes no focus, so a screen reader would lose exactly what the rule
     set out to keep.
   Controls the reader sets — a checkbox, a radio — wear the accent. It is
   the colour of where the reader acts, which is the same reason the primary
   button wears it, so this is not a fourth use of the gold but the first one
   read properly. Set here once because it was four scoped rules in the
   console and four controls that had missed all of them, left wearing the
   browser's blue, which is nobody's colour in a violet and gold room. A
   control set by something other than the reader overrides it deliberately.
   Scrollbars follow the theme in two moves. `color-scheme` in tokens.css is
   the first and it does most of the work for free: the browser paints its
   own bars, form controls and default grounds in the matching variant.
   `scrollbar-color` here is the second, quieting the thumb to the house's
   own. It inherits, which is what this console needs — a pane on the
   terminal ground is dark in both themes, so it overrides with --term-scroll
   and the rule above it never has to know which panes those are. Deliberately
   not ::-webkit-scrollbar: Firefox ignores it, so the standard would have to
   be written anyway, and the day you use it Chrome stops drawing overlay
   scrollbars on macOS — the look changes and the layout changes with it.
   .stamp — the golden state seal (INSERTED): accent plate, condensed
     uppercase; whoever places it tilts and positions it. This is why a
     chip's plate is a 16% tint and never a saturated fill: nothing may
     compete with the seal. */
.cart-ref{display:inline-flex;align-items:center;gap:6px;white-space:nowrap;font-family:var(--cond);font-weight:600;letter-spacing:.1em;text-transform:uppercase;font-size:11px;padding:2px 7px;border-radius:2px;border:1px solid var(--line);color:var(--muted);background:none;cursor:pointer;text-decoration:none}
.cart-ref::before{content:"";width:7px;height:7px;border-radius:50%;border:1.5px solid var(--soft);box-sizing:border-box;flex:none}
.cart-ref.in{color:var(--ink)}
.cart-ref.in::before{background:var(--good);border-color:var(--good)}
.cart-ref:hover:not(.unknown),.cart-ref:focus-visible:not(.unknown){border-color:var(--ink);outline:none}
.cart-ref.unknown{border-style:dashed;text-decoration:line-through;cursor:default;opacity:.7}
.door-ref,.probe-ref{display:inline-flex;align-items:center;gap:8px;white-space:nowrap;color:var(--ink);text-decoration:none}
.door-ref b,.probe-ref b{font-family:var(--cond);font-weight:600;letter-spacing:.1em;text-transform:uppercase;font-size:11px;color:var(--muted)}
.door-ref span,.probe-ref span{font-family:var(--mono);font-size:12px}
/* The box, and everything it implies: this is the whole difference between
   the two, and the reason a probe may never grow one. */
.door-ref{padding:3px 9px;border:1px solid var(--line);border-radius:2px;background:none;cursor:pointer}
.door-ref:hover:not(.unlit),.door-ref:focus-visible:not(.unlit){border-color:var(--ink);outline:none}
.chip{display:inline-flex;align-items:center;gap:5px;white-space:nowrap;font-family:var(--mono);font-weight:500;font-size:11px;padding:2px 8px;border-radius:3px;border:0;background:var(--surface-2);color:var(--muted)}
.chip.good{background:color-mix(in srgb,var(--good) 16%,transparent);color:var(--good)}
.chip.warn{background:color-mix(in srgb,var(--warn) 16%,transparent);color:var(--warn)}
.chip.bad{background:color-mix(in srgb,var(--bad) 16%,transparent);color:var(--bad)}
.chip.off{background:none;color:var(--soft)}
.chip.busy::before{content:"";width:6px;height:6px;border-radius:50%;background:currentColor;flex:none;animation:chip-pulse 1s infinite}
@keyframes chip-pulse{50%{opacity:.25}}
@media (prefers-reduced-motion: reduce){.chip.busy::before{animation:none}}
.unlit,[disabled],[aria-disabled="true"]{opacity:.45;cursor:not-allowed}
/* Never pointer-events:none here: it takes the title with it, and the title
   is the reason. What must not fire is prevented where it is bound. */
.unlit,[aria-disabled="true"]{pointer-events:auto}
input[type="checkbox"],input[type="radio"]{accent-color:var(--accent)}
:root{scrollbar-color:var(--scroll) transparent}
.stamp{display:inline-block;font-family:var(--cond);font-weight:700;letter-spacing:.14em;text-transform:uppercase;font-size:10.5px;color:var(--accent-ink);background:var(--accent);padding:3px 8px;border-radius:2px;transform:rotate(8deg);box-shadow:0 2px 4px rgba(0,0,0,.3)}
"""

# --- favicon.svg ---------------------------------------------------------------
# The tab's mark: the band's own lockup at 16 pixels — the workbench in
# board-ink on a full-bleed board plate. The plate is not decoration. The
# mark is fill="currentColor" (see console_live.ex, which inlines it so it
# takes the band's ink), and a favicon has no band to take ink from: left on
# transparent it renders black on a light tab strip and disappears on a dark
# one. The plate is what gives it its own ink, and the colour is the one
# thing that survives at 16 pixels, where DEW and the drawers are already
# noise and only the silhouette and the violet still say whose tab this is.
# Not gold: the accent has three uses and a tab is none of them.
#
# The mark comes in from the file it lives in rather than being pasted here,
# for the same reason the console reads it instead of holding a copy. The
# padding is 1/16 of the tile — measured at 16 px against 0, 2, 6 and 8:
# tighter and the bench's legs sit on the tile's edge as if cropped, wider
# and the drawing shrinks into a blur.
#
# favicon.ico beside it is the fallback for what does not take an SVG icon,
# rendered from this file once and committed, since it only changes when the
# mark does:
#     inkscape --export-type=png --export-filename=<n>.png --export-width=<n> \
#              --export-height=<n> console/priv/static/favicon.svg   # 16, 32, 48
#     magick 16.png 32.png 48.png console/priv/static/favicon.ico
MARK = os.path.join(ROOT, "console", "priv", "static", "images", "logo.svg")

def favicon_svg(tile=64, pad=4):
    mark = open(MARK).read()
    box = re.search(r'viewBox="0 0 (\d+) (\d+)"', mark)
    side = max(int(box.group(1)), int(box.group(2)))
    inner = textwrap.dedent(re.search(r"<svg[^>]*>(.*)</svg>", mark, re.S).group(1)).strip("\n")
    scale = (tile - 2 * pad) / side
    return (f'<!-- generated by assets/design/build.py from assets/design/tokens.json and\n'
            f'     console/priv/static/images/logo.svg — edit those, not this -->\n'
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {tile} {tile}" '
            f'fill="{role("board-ink", "light")}">\n'
            f'  <rect width="{tile}" height="{tile}" fill="{role("board", "light")}"/>\n'
            f'  <g transform="translate({pad},{pad}) scale({scale:.8f})">\n'
            + "\n".join("    " + line for line in inner.splitlines()) + "\n  </g>\n</svg>\n")

# The console links tokens.css and components.css from its own static
# directory: the same two projections, written twice, and --check keeps
# the copies honest.
CONSOLE_CSS = os.path.join(ROOT, "console", "priv", "static", "assets", "css")
outputs = {
    os.path.join(GEN, "tokens.css"): tokens_css(),
    os.path.join(GEN, "components.css"): components_css(),
    os.path.join(CONSOLE_CSS, "tokens.css"): tokens_css(),
    os.path.join(CONSOLE_CSS, "components.css"): components_css(),
    os.path.join(GEN, "diagram-design.md"): "<!-- generated by assets/design/build.py from assets/design/tokens.json — edit the tokens, not this -->\n" + guide(),
    os.path.join(ROOT, "console", "priv", "static", "favicon.svg"): favicon_svg(),
}
profiles = os.path.expanduser("~/.diagram-design/profiles")
installed = os.path.join(profiles, "workbench.md")
marker = os.path.join(ROOT, ".diagram-design")

stale = []
for path, content in outputs.items():
    if CHECK:
        if not os.path.isfile(path) or open(path).read() != content: stale.append(path)
    else:
        os.makedirs(os.path.dirname(path), exist_ok=True); open(path, "w").write(content)

body = guide()
if CHECK:
    if not os.path.isfile(installed) or re.sub(r"^<!--.*?-->\n", "", open(installed).read(), flags=re.S) != body: stale.append(installed)
    if not os.path.isfile(marker) or open(marker).read() != "profile: workbench\n": stale.append(marker)
else:
    os.makedirs(profiles, exist_ok=True)
    # Keep the current profile's created date when it has one.
    if os.path.isfile(installed):
        m = re.search(r"^created: (\S+)$", open(installed).read(), re.M)
        text = profile(body)
        if m: text = re.sub(r"^created: \S+$", f"created: {m.group(1)}", text, count=1, flags=re.M)
    else:
        text = profile(body)
    open(installed, "w").write(text)
    open(marker, "w").write("profile: workbench\n")
    # The skill's recovery copy of its pristine guide, if it is not there yet.
    default = os.path.join(profiles, "default.md")
    if not os.path.isfile(default):
        for cand in sorted(__import__("glob").glob(os.path.expanduser("~/.claude/plugins/cache/diagram-design/diagram-design/*/skills/diagram-design/references/style-guide.md"))):
            pristine = open(cand).read()
            if not pristine.startswith("<!-- diagram-design-profile") and "#f5f5f5" in pristine:
                today = datetime.date.today().isoformat()
                open(default, "w").write(f"<!-- diagram-design-profile\nname: Default\nslug: default\nsource-url: none\ncreated: {today}\nupdated: {today}\nnotes: Pristine shipped style guide\n-->\n" + pristine)
                break

if CHECK:
    if stale:
        print("stale:", *stale, sep="\n  "); sys.exit(1)
    print("design projections are current")
else:
    print("wrote", *outputs, installed, marker, sep="\n  ")
