#!/usr/bin/env python3
"""The house's design tokens, projected to whoever consumes them.

    ./assets/design/build.py            write every projection
    ./assets/design/build.py --check    exit 1 if any projection is stale

Reads tokens.json — the one source — and writes, marked as generated:

  generated/tokens.css          custom properties for the console (light on
                                :root, dark under prefers-color-scheme guarded
                                by :root:not([data-theme="light"]), and again
                                under :root[data-theme="dark"])
  generated/components.css      the house's components — the cartridge ref
                                (a mention of a cartridge: state dot, name,
                                always the door to its detail), the door (an
                                address — a route the project offers or a
                                port the compose publishes — with what it
                                answered attached), the commit ref and the
                                stamp (the golden state seal) — consumed by
                                the console mock, the LiveView console and
                                the box-back plates
  ../../console/priv/static/favicon.svg
  ../../console/priv/static/images/icons.svg   the sprite of marks, from icons/*.svg
                                the tab's mark: the workbench's own logo.svg
                                in board-ink on a board plate, because a mark
                                drawn in currentColor has no band to take ink
                                from in a tab strip
  generated/diagram-design.md   the diagram-design skill's style guide, with
                                the house's roles and type mapped onto its
                                semantic roles; also installed as the profile
                                ~/.diagram-design/profiles/workbench.md, which
                                the repository's .diagram-design marker names

Run from the repository root.
"""
import json, os, re, sys, datetime, shutil, textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
GEN = os.path.join(HERE, "generated")
CHECK = "--check" in sys.argv
T = json.load(open(os.path.join(HERE, "tokens.json")))
PALETTE = {k: v["value"] for k, v in T["palette"].items()}

# `{violet}` is a palette entry; `{warn:dark}` is another role's value in one
# theme. The second form exists for the roles that ARE another role read on a
# ground that does not follow the theme — the band's three — so the value is
# never copied by hand into a second place, where it would drift.
def resolve(v):
    def one(m):
        key = m.group(1)
        if ":" in key:
            name, mode = key.split(":", 1)
            return role(name, mode)
        return PALETTE[key]

    return re.sub(r"\{([\w:-]+)\}", one, v)

def role(name, mode):
    r = T["roles"][name]
    return resolve(r["value"] if "value" in r else r[mode])

def hex_to_rgb(h):
    h = h.lstrip("#"); return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))

def rgba(h, a):
    return "rgba(%d,%d,%d,%s)" % (*hex_to_rgb(h), a)

HEADER = "/* generated by assets/design/build.py from assets/design/tokens.json — edit the tokens, not this */\n"

# --- tokens.css ----------------------------------------------------------------
def css_block(mode, indent):
    lines = []
    for name, r in T["roles"].items():
        if "value" in r and mode == "dark":
            continue  # one value, both themes: written once on :root
        lines.append(f"{indent}--{name}:{role(name, mode)};")
    if mode == "light":
        for key, f in T["type"].items():
            lines.append(f'{indent}--{f["css"]}:"{f["family"]}",{f["fallback"]};')
    return "\n".join(lines)

# `color-scheme` rides along in each of the three blocks rather than being
# written once by hand somewhere. It has to switch exactly when the roles
# switch — it is what makes the browser paint its own scrollbars, form
# controls and default grounds in the matching variant — and a hand-written
# copy of this three-state dance would be one more thing to forget the day
# the dance changes.
def tokens_css():
    return (HEADER +
            ":root{\n  color-scheme: light;\n" + css_block("light", "  ") + "\n}\n"
            "@media (prefers-color-scheme: dark){\n  :root:not([data-theme=\"light\"]){\n    color-scheme: dark;\n" + css_block("dark", "    ") + "\n  }\n}\n"
            ":root[data-theme=\"dark\"]{\n  color-scheme: dark;\n" + css_block("dark", "  ") + "\n}\n")

# --- the diagram skill's style guide -------------------------------------------
# The skill thinks in paper/ink/muted/soft/rule/accent/link; the house in
# ground/surface/ink/muted/line/accent. The mapping, with its reasons:
#   paper      <- ground     the page; the diagram sits on it
#   paper-2    <- surface-2  the framed variant's container
#   ink/muted/soft/link/accent <- the same roles
#   rule       <- line       hairlines; the skill's rule is ink at 12%, ours a hex
#   rule-solid <- muted at 45%
#   accent-tint<- accent at 10% (light) / 14% (dark), as accent-soft
#   title      <- text (Source Serif 4): the serif the backs are set in
#   node-name  <- display (Barlow Condensed): the band's lettering
#   sublabel/eyebrow/arrow-label <- code (IBM Plex Mono)
def guide():
    L = lambda n: role(n, "light"); D = lambda n: role(n, "dark")
    disp, text, code = T["type"]["display"]["family"], T["type"]["text"]["family"], T["type"]["code"]["family"]
    fonts = T["google-fonts"]
    return f"""# Style Guide

**The single source of truth for colors, typography, and tokens** of this
install — generated from the workbench's `assets/design/tokens.json` by
`assets/design/build.py`. Edit the tokens there and rebuild; never edit
this file.

The skin is the Dockerized Elixir Workbench's: a violet-tinted ground,
violet-black ink, the gold of the seal as the one accent, the band's
condensed lettering for names and the backs' serif for titles.

---

## Tokens

### Semantic roles

Every token is referred to by **semantic role**, not by its hex value. Type references (`type-*.md`) and SKILL.md say `accent`, not a hex.

| Role | Purpose | Default (light) | Default (dark) |
|---|---|---|---|
| `paper` | Page background, default node fill | `{L("ground")}` | `{D("ground")}` |
| `paper-2` | Diagram container bg, secondary fill | `{L("surface-2")}` | `{D("surface-2")}` |
| `ink` | Primary text, primary stroke | `{L("ink")}` | `{D("ink")}` |
| `muted` | Secondary text, default arrow stroke | `{L("muted")}` | `{D("muted")}` |
| `soft` | Sublabels, boundary labels | `{L("soft")}` | `{D("soft")}` |
| `rule` | Hairline borders | `{L("line")}` | `{D("line")}` |
| `rule-solid` | Stronger borders, baselines | `{rgba(L("muted"), 0.45)}` | `{rgba(D("muted"), 0.45)}` |
| `accent` | Focal / 1–2 max per diagram | `{L("accent")}` | `{D("accent")}` |
| `accent-tint` | Fill for accent-bordered boxes | `{L("accent-soft")}` | `{D("accent-soft")}` |
| `link` | HTTP/API calls, external arrows | `{L("link")}` | `{D("link")}` |

> **Brand palette source:** the workbench's palette — `violet {PALETTE["violet"]}` (the covers' board), `gold {PALETTE["gold"]}` (the seal; `{PALETTE["gold-deep"]}` on light ground), and the violet-tinted greys the console reads on. `board` (`{PALETTE["violet"]}`) is not a diagram role: it is the band and the covers, and a node painted in it would read as a box, not a component.

### Inversion rule (light → dark)

Any `rgba(29,20,36, X)` in light becomes `rgba(239,231,242, X)` in dark. Same opacities, RGB flipped. The accent brightens from the deep gold to the seal's gold on dark paper.

### Series palette (multi-series chart types only)

The workbench's service colours, which its logs already use to tell services apart; `accent` stays reserved for the focal series.

| Token | Light | Dark | Notes |
|---|---|---|---|
| `series-1` | `{role("svc-compute","light")}` | `{role("svc-compute","light")}` | compute: the app |
| `series-2` | `{role("svc-database","light")}` | `{role("svc-database","light")}` | database |
| `series-3` | `{role("svc-devtools","light")}` | `{role("svc-devtools","light")}` | devtools: pgAdmin, Adminer |
| `series-4` | `{role("svc-balancer","light")}` | `{role("svc-balancer","light")}` | the balancer |
| `series-5` | `{role("svc-network","light")}` | `{role("svc-network","light")}` | network: the pod container |

Fills sit at `0.18` opacity light, `0.22` dark; strokes use the full color. **Don't backfill these tokens to non-chart types.**

### Terminal skin (opt-in alternate)

The console's own terminal, for the terminal-window primitive (see [primitive-terminal.md](primitive-terminal.md)).

| Token | Hex | Purpose |
|---|---|---|
| `terminal-page` | `{D("ground")}` | Page background behind the window |
| `terminal-paper` | `{role("term","light")}` | Window body, node fill |
| `terminal-bar` | `{role("term-line","light")}` | Titlebar strip |
| `terminal-border` | `{role("term-line","light")}` | Window border, hairlines |
| `terminal-ink` | `{role("term-ink","light")}` | Primary text, primary stroke |
| `terminal-muted` | `{role("term-dim","light")}` | Secondary text, sublabels, ring stroke |
| `terminal-soft` | `{D("soft")}` | Tertiary — inactive dots, spokes |
| `terminal-accent` | `{D("accent")}` | The one accent — focal station, prompt sign, active dot |
| `terminal-accent-tint` | `{D("accent-soft")}` | Fill for accent-bordered boxes |

**1-accent rule still holds.**

---

## Typography

| Role | Family | Size | Weight | Usage |
|---|---|---|---|---|
| `title` | {text} | 1.75rem | 400 | Page H1 |
| `node-name` | {disp} | 13px | 600, tracked 0.04em | Human-readable labels |
| `sublabel` | {code} | 9px | 400 | Port, protocol, URL, field type |
| `eyebrow` | {code} | 7–8px | 500, tracked 0.18em, uppercase | Type tags, axis labels |
| `arrow-label` | {code} | 8px | 400, tracked 0.06em | Arrow annotations |
| `callout` | {text} *italic* | 14px | 400 | Editorial asides only |

### Font stack

```html
<link href="{fonts}" rel="stylesheet">
```

**Load-bearing rule:** Mono is for *technical* content (ports, commands, URLs, field types). Names go in {disp} — the band's lettering, so a node reads like a label on the machine. Page title is {text}. Italic {text} is reserved for annotation callouts (see [primitive-annotation.md](primitive-annotation.md)). **Never JetBrains Mono** as a blanket "dev" font.

---

## Stroke, radius, spacing

| Token | Value | Use |
|---|---|---|
| `stroke-thin` | `0.8` | Tag-box outlines, leaf nodes |
| `stroke-default` | `1` | Most strokes |
| `stroke-strong` | `1.2` | Emphasis strokes |
| `radius-sm` | `4` | Small tags |
| `radius-md` | `6` | Node boxes |
| `radius-lg` | `8` | Containers, rings |
| `grid` | `4` | Every coord, size, and gap is divisible by 4 (hard rule) |

---

## Node type → treatment

Semantic role combinations — reference these by name in type specs.

| Type | Fill | Stroke |
|---|---|---|
| `focal` (1–2 max) | `accent-tint` | `accent` |
| `backend` | `{L("surface")}` (surface; `{D("surface")}` dark) | `ink` |
| `store` | `ink @ 0.05` | `muted` |
| `external` | `ink @ 0.03` | `ink @ 0.30` |
| `input` | `muted @ 0.10` | `soft` |
| `optional` | `ink @ 0.02` | `ink @ 0.20` dashed `4,3` |
| `security` | `accent @ 0.05` | `accent @ 0.50` dashed `4,4` |

---

## Customizing the skin

This guide is a projection of `assets/design/tokens.json` in the workbench repository: change the tokens and run `./assets/design/build.py`, which rewrites this file and the installed profile.

### Constraints (don't break these)

- **Contrast**: `ink` must hit WCAG AA on `paper`. `muted` must hit AA on `paper` for 11px+ text.
- **One accent**: the seal's gold. Two accents erases the focal signal.
- **No rainbow palette**: the service colours are for series only.
- **Serif + condensed + mono**: three families, not more.
- **Dot pattern is optional, not default.**
- **Container is clean by default.**
"""

def profile(body):
    today = datetime.date.today().isoformat()
    return (f"<!-- diagram-design-profile\nname: {T['name']}\nslug: workbench\nsource-url: none\n"
            f"created: 2026-08-29\nupdated: {today}\nnotes: generated from assets/design/tokens.json by assets/design/build.py\n-->\n" + body)

# --- write or check --------------------------------------------------------------
# --- components.css ------------------------------------------------------------
def components_css():
    return HEADER + """/* The house's components — notation, not layout. Anything that mentions
   a cartridge, anywhere, wears the same reference; the state seal is the
   one golden thing. Both consoles and the box-back plates read these.

   .cart-ref — a mention of a cartridge, always a link to its detail.
     bare     on the shelf, not inserted (hollow dot)
     .in      inserted (good dot)
     .unknown no such cartridge (dashed, struck, no link)
     Never gold: the accent belongs to the stamp. On a printed back
     plate use the state-free bare form — a plate knows no project.
   .pkg-ref — a mention of an Elixir package: hex's own mark, then the
     name in mono, because it is a name read off mix.exs. The mark is
     what says it is a link — no underline, nothing that stretches —
     and it is dimmed until the mention is hovered, so a column of them
     does not shout. It goes wherever a dependency is named, and it
     addresses one of two places: the package's page on hex.pm (the
     name), or one version's documentation on hexdocs (the version,
     `.pkg-ref.bare`, which drops the mark where the row already wears
     one). A cartridge is mentioned with .cart-ref and a package with
     this: the first opens a drawer in this console, the second leaves
     for somebody else's site, and the reader should never have to
     press to learn which.
   .door-ref — an address: a route the project offers on the app's port
     (exdoc's /dev/docs, mailer's /dev/mailbox, health_probe's
     {path}/live) or a port the compose publishes for a service
     (localhost:4001, database:5432). One order wherever it is read — the
     label first, in the house's lettering because it is a name, then the
     address in mono because it is read off the machine. Who opened it is
     not part of it: that is a mention of a cartridge, so it goes beside
     as a .cart-ref and opens that box with the same click. The console
     had this twice with the two halves swapped — <small> was the
     cartridge in the rail and the door's own name on the box, so learning
     one taught the reader the other wrong.
     The layer, as an 8px square before the label — the mark the logs'
     service filter already uses, meaning "which layer answers here":
       .door-route  (default) violet, addr-route: a route the project offers
       .door-port   blue, addr-port: a port the compose publishes on the host
       .door-inside the same blue, hollow: a port inside the pod, no door on
                    the host (database:5432) — the layer kept, the opening not
       .door-output green, addr-output: a page a tool wrote on disk (doc/,
                    cover/), served by the console on an origin of its own;
                    written as the dir it is read from, its reading the whole
                    stamp of when it was built and nothing more
                    (2026-09-22 18:18 +0200: a page is read against the project
                    of that moment, and an hour alone left the day and the
                    clock to be guessed; that there IS a stamp is what says it
                    was built, and where there is none the door offers build) — never knocked, it
                    answers with the app down. Where the page is not there
                    yet, the reading's place takes the one thing to do
                    instead: .read.build, the same plate pressable, which
                    runs the command the cartridge names (./wb.sh mix docs)
                    and is the only door that does something other than open
     (prefixed, because `.console` is the LiveView console's own root.)
     A route is written on its port — <span><em>:4001</em>/dev/mailbox</span>,
     the port dimmed — because it rides on one; a port is written whole.
     What answered when it was called goes *inside* the border, attached
     at the right edge: <i class="read good">200</i> — the chip's plate and
     voice (mono, lower case, a 16% tint) behind the border's own 1px
     line, so a reading in a wrapping row can never drift to the wrong
     door. Absent when nothing called it; .busy while asking. A port's
     reading is what its healthcheck said (healthy, running), a route's
     the HTTP code. This attached reading is the one place a chip's
     plate sits inside a pressable box: it is the box's face, not a
     target of its own.
     The states are the house's own, not its: pressable while something
     answers, .unlit with the reason in the title when nothing does — the
     app is down, the cartridge is not inserted. An unlit door drops its
     href as well. .unlit cannot stop a link, and by its own rule what
     must not fire is prevented where it is bound.
     There is no probe any more. .probe-ref was the door minus the box
     for "an address the console polls", and nothing ever polled: the
     project owes the workbench nothing, a health endpoint is a route it
     has for its own reasons, and the console reads it and calls it like
     any other door (settled 2026-09-08 with the Record paper; the page
     that had split them, puertas-y-sondas, retires with it).
   .commit-ref — a mention of a commit, the third reference beside the
     cartridge and the door: the short sha in mono, in a 1px box because
     it is pressed — it opens History on that commit with its diff — and
     with no dot, because a commit has no state to mark. The subject and
     the date go in the title. Wherever a sha is written: the Record's
     birth, the origin chip, the rail's HEAD, History's own rows. Not on
     a ribbon's sublabel, which is small text and no box.
   .chip — a reading the console reports: a container's health, a job's
     exit code, the edition of a box. It is deliberately nothing like the
     mention, which it once was to the declaration: the two say different
     kinds of thing and had grown the same face. Two things separate them
     now. Shape — a bordered box with a dot is a door you press; a chip is
     never pressable, so it has neither. Voice — mono in lower case, which
     in the console already means read off the machine, where the house's
     condensed uppercase means a name. The dot survives on one thing only,
     .busy, where it means something is moving.
     bare    a fact with no state: v0.2.0, base, collection
     .good/.warn/.bad  a state, on a plate tinted from its colour
     .off    an absence — not baked, idle, nothing is up: no plate at all.
             It keeps the plated chips' padding even so. The plate is what
             it drops, not the space: these read in columns beside their
             plated siblings — baked over not baked, running over down —
             and a narrower padding gave the same column two left edges
             depending on the state of the row. What the reader should see
             changing between two rows is the plate and the word, never
             where the word starts.
     .busy   with one of the above: the dot comes back, and pulses
   .unlit — the house's one way of saying not available. The rule it
     carries: never hide what the reader could have. A control they could
     make appear stays where it is, wearing this, with the reason in its
     title and, where there is one, the action that would light it; a tab
     the console can show is part of its map whether or not it can be
     opened today. Hiding is only for what is not applicable and never
     will be here. The console lights up when a cartridge is inserted —
     this is that verb, negated, and it is why the name is not `off`,
     which a chip already uses for something else: a chip reports an
     absence out in the world (not baked, idle), .unlit marks a control
     you cannot use yet. Applies equally to [disabled] and to
     aria-disabled, which is what a tab must use: a disabled <button>
     takes no focus, so a screen reader would lose exactly what the rule
     set out to keep.
   Controls the reader sets — a checkbox, a radio — wear the accent. It is
   the colour of where the reader acts, which is the same reason the primary
   button wears it, so this is not a fourth use of the gold but the first one
   read properly. Set here once because it was four scoped rules in the
   console and four controls that had missed all of them, left wearing the
   browser's blue, which is nobody's colour in a violet and gold room. A
   control set by something other than the reader overrides it deliberately.
   Scrollbars follow the theme in two moves. `color-scheme` in tokens.css is
   the first and it does most of the work for free: the browser paints its
   own bars, form controls and default grounds in the matching variant.
   `scrollbar-color` here is the second, quieting the thumb to the house's
   own. It inherits, which is what this console needs — a pane on the
   terminal ground is dark in both themes, so it overrides with --term-scroll
   and the rule above it never has to know which panes those are. Deliberately
   not ::-webkit-scrollbar: Firefox ignores it, so the standard would have to
   be written anyway, and the day you use it Chrome stops drawing overlay
   scrollbars on macOS — the look changes and the layout changes with it.
   Where the bar is drawn is not a colour but it is the house's too: on the
   edge of the box that scrolls, with nothing between the two. The browser
   already puts it there; what moves it is padding on a wrapper *around*
   the scroller, which is how the console's panes came to carry their bars
   at 28px, 32px and half a modal in from the edge. So the side air of a
   pane goes on the element that scrolls, or on what it holds — never on
   a wrapper — and a measure (max-width) goes on the content, never on the
   scroller. A box with its own border (a terminal, a pre) is a box that
   scrolls, and its bar sits on its own inner edge by the same rule. And
   every pane that can scroll says `scrollbar-gutter:stable`, so nothing
   under it steps sideways the moment the bar appears.
   Selected text is the board, turned to face the ground it lands on.
     The browser's blue was the last place it was still leaking in — the
     same blue the checkboxes wore before accent-color, and the one
     Phoenix's progress bar wore before the band's rule took its job. It
     needs no colour of its own: a selection is text on a solid ground,
     and the house has had exactly one pair for that from the start,
     `violet` and `violet-ink`. Which is also why it is not gold: a
     selection can cover half a page, and nothing may compete with the
     seal.
     And it is a VEIL, not a block. Turning the pair over — a solid
     violet band with pale words — was legible at 11.4:1 and far louder
     than what it is, and it flattened everything it covered: a log line
     loses its service colour under it, a config file its keys. Selected
     text keeps its own ink and takes a wash of the board behind it, so
     what was coloured stays coloured. That is why there is one role
     here and not two.
     What the wash is made of follows the theme, and the two alphas are
     tuned rather than shared, so that the grounds *feel* the same
     instead of sharing a number: violet at .22 over a light ground
     reads 1.50:1 against it, the pale ink at .15 over a dark one reads
     1.48:1. `accent-soft` already plays that trick, for the same
     reason.
     And the fold this file always makes: a ground that does not follow
     the theme does not follow this either. The band and the terminal
     panes are dark under both, so each washes with its OWN ink —
     color-mix with `board-ink`, with `term-ink` — which needs no token
     of its own and cannot come apart from the ground it sits on.
   Controls the reader sets, again: a <select>'s own list. A native one
     hands its popup to the operating system, and for years the only
     thing a page could say about it was `color-scheme` — light or dark,
     and no more: the hover stayed the system's blue and the scrollbar
     the system's grey, in a room that is neither. Chrome's customizable
     select (`appearance: base-select`) puts the popup back inside the
     page, where the house can dress it: the accent's own tint for the
     row under the pointer, the surface it sits on, the house's thumb on
     its scrollbar, and the group labels in the condensed uppercase every
     other heading uses. It is written behind @supports, so a browser
     that has not got it keeps exactly the control it has today —
     `color-scheme` in tokens.css still gets that one the right half of
     the theme, which is all it ever could.
   .nothing — a place with nothing in it. The prose form of what
     .chip.off says in a word: an absence out in the world, not a
     failure and not a control you cannot use yet.
     One rule, and it is about the sentence rather than the face:
     **an empty place says what is missing and what would fill it.**
     Not "no data" — *No containers: the project is down. Deploy → Up.*
     *Nothing inserted yet: the shelf is in Cartridges.* *Cartridges open
     doors here: docs, dashboard, mailbox…* The console wrote half of
     them that way already and the other half as bare statements; the
     class is what makes the good half the rule.
     It is never a box. An absence with a border drawn round it is a
     thing, and there is no thing. That is one dashed rectangle gone.
     And it says its own type as well as its own ink: it is a sentence,
     not a reading, so it is the house's serif wherever it lands — in a
     table of mono rows too, where being the one line that is not mono
     is what says it is not a row.
     It takes the quiet ink of whatever ground it is on — the house's
     `--muted`, or `--term-dim` on the panes that are dark in both
     themes, which is the same split the scrollbars already make. Six
     declarations said this before: .note doing double duty, td.muted,
     two .empty, a .missing with its border, and two ::before contents.
   .fetch — a field whose values are not the workbench's. They come from
     outside it, over the network, and somebody has to go and get them:
     the square button flush against the field is who goes. It takes its
     width out of the field, so the pair is exactly as wide as the field
     was and the form keeps its column; it wears a reload, because that
     is what it does; and it turns while it is away. Give the pair the
     field's own font-size: the button is 2.5em wide, which is what a
     field of that type is tall — padding, border and a line of it — so
     the square follows the type scale instead of a measured pixel.
     It stands one field-padding away and not welded to it. A select
     carries its own chevron at that very edge, and a button soldered
     there put two glyphs side by side with nothing to say which one
     belonged to the field. The gap is what says they are two things:
     the field is a value you pick, the button is an errand that costs
     seconds and leaves the machine.
     The rule it carries is the reason it exists: **a field like this
     never goes on its own.** Opening the drawer that holds one costs
     nothing, and there is no clock behind it — the trip happens when the
     button is pressed, so every call the console makes to the internet
     is one the reader can point at. What it brings back is held for the
     whole console until somebody presses again; being a day old is not
     a reason to go, and a list that never arrived says so where the
     field's help is, rather than reading as a list with nothing in it.
     Until then the field shows what is configured and is not pretending
     to be a choice: one option, its own.
   .sq — the square icon button: a mark from the sprite, a name for the
     reader, the field's height; .small is a line's, for a bar or a row.
   .fold — the control that opens and closes something: a section of the
     rail, a file in a diff, a job in the tray. Two rules, and they are
     the whole component. The caret CLOSES the line: it is the last thing
     on it, pushed to the end, so what the row is about keeps the left
     edge every other line in the column has — a head that led with its
     caret sat 19px in from the rail's own margin, and the names stopped
     lining up with everything above them. It ends where the actions end,
     which is where the eye already goes for a control. And it is DRAWN
     FROM aria-expanded, never typed into the template — the attribute a
     screen reader reads is the one that draws the arrow, so the two
     cannot come to say different things, which is what happens the day
     a template toggles a class and forgets the character beside it.
     Everything else belongs to where it is used: a section head is
     condensed uppercase, a job row is mono, a file row is a path. This
     sets the control and the caret and nothing else — and it inherits
     the type of what it sits in whole, which takes three declarations
     and not one: the browser restyles a form control, and `font:
     inherit` does not reach `letter-spacing` or `text-transform`. A
     fold made of the rail's heads lost their versals and their tracking
     the day it became a button, and the house's own rule went with
     them: condensed uppercase is how a NAME is written here.
     The caret is the one thing that does NOT inherit the size. A rail
     head is 11px and a job row is small mono, and an arrow set in the
     row's own type came out around nine pixels — a dot, not an arrow,
     in every one of the three places it is used. So it is given its
     own size, above the line it closes and with a floor under it, so
     the arrow is the same arrow in a 15px head and in a 12px job row —
     it is a control and not type. `line-height: 1` keeps the taller
     glyph from growing the row it sits in.
   .stamp — the golden state seal (INSERTED): accent plate, condensed
     uppercase; whoever places it tilts and positions it. This is why a
     chip's plate is a 16% tint and never a saturated fill: nothing may
     compete with the seal. */
.cart-ref{display:inline-flex;align-items:center;gap:6px;white-space:nowrap;font-family:var(--cond);font-weight:600;letter-spacing:.1em;text-transform:uppercase;font-size:11px;padding:2px 7px;border-radius:2px;border:1px solid var(--line);color:var(--muted);background:none;cursor:pointer;text-decoration:none}
.cart-ref::before{content:"";width:7px;height:7px;border-radius:50%;border:1.5px solid var(--soft);box-sizing:border-box;flex:none}
.cart-ref.in{color:var(--ink)}
.cart-ref.in::before{background:var(--good);border-color:var(--good)}
.cart-ref:hover:not(.unknown),.cart-ref:focus-visible:not(.unknown){border-color:var(--ink);outline:none}
.cart-ref.unknown{border-style:dashed;text-decoration:line-through;cursor:default;opacity:.7}
/* A package of the ecosystem: hex's mark carries the link, so nothing
   is underlined and nothing stretches. The mark is an <img> and not a
   sprite symbol, because it is six fixed colours and takes none of ours. */
.pkg-ref{display:inline-flex;align-items:center;gap:5px;white-space:nowrap;font-family:var(--mono);font-size:12px;color:var(--ink);text-decoration:none;background:none;border:0;padding:0;cursor:pointer}
.pkg-ref:hover,.pkg-ref:focus-visible{color:var(--accent);outline:none}
.pkg-ref .mark{width:12px;height:11px;flex:none;opacity:.55;transition:opacity 120ms}
.pkg-ref:hover .mark,.pkg-ref:focus-visible .mark{opacity:1}
.door-ref{display:inline-flex;align-items:center;gap:8px;white-space:nowrap;color:var(--ink);text-decoration:none;padding:3px 9px;border:1px solid var(--line);border-radius:2px;background:none;cursor:pointer}
.door-ref b{font-family:var(--cond);font-weight:600;letter-spacing:.1em;text-transform:uppercase;font-size:11px;color:var(--muted)}
.door-ref span{font-family:var(--mono);font-size:12px}
.door-ref span em{font-style:normal;color:var(--soft)}
.door-ref:hover:not(.unlit),.door-ref:focus-visible:not(.unlit){border-color:var(--ink);outline:none}
/* The layer square: the logs' 8px service swatch, saying which layer answers. */
.door-ref::before{content:"";width:8px;height:8px;border-radius:2px;flex:none;background:var(--addr-route)}
.door-ref.door-port::before{background:var(--addr-port)}
.door-ref.door-inside::before{background:none;box-shadow:inset 0 0 0 2px var(--addr-port)}
.door-ref.door-output::before{background:var(--addr-output)}
/* The reading, attached inside the border: the chip's plate behind the box's own line. */
.door-ref:has(.read){padding-right:0}
.door-ref .read{display:inline-flex;align-items:center;gap:5px;align-self:stretch;margin:-3px 0 -3px 1px;padding:3px 8px;border-left:1px solid var(--line);border-radius:0 2px 2px 0;font-family:var(--mono);font-style:normal;font-weight:500;font-size:11px;background:var(--surface-2);color:var(--muted)}
.door-ref .read.good{background:color-mix(in srgb,var(--good) 16%,transparent);color:var(--good)}
.door-ref .read.warn{background:color-mix(in srgb,var(--warn) 16%,transparent);color:var(--warn)}
.door-ref .read.bad{background:color-mix(in srgb,var(--bad) 16%,transparent);color:var(--bad)}
.door-ref .read.busy::before{content:"";width:6px;height:6px;border-radius:50%;background:currentColor;flex:none;animation:chip-pulse 1s infinite}
.door-ref .read.build{border-top:0;border-right:0;border-bottom:0;cursor:pointer;color:var(--ink);text-transform:none}
.door-ref .read.build:hover,.door-ref .read.build:focus-visible{background:var(--ink);color:var(--surface);outline:none}
.commit-ref{display:inline-block;font-family:var(--mono);font-size:11.5px;letter-spacing:0;text-transform:none;color:var(--ink);padding:1px 7px;border:1px solid var(--line);border-radius:2px;background:none;text-decoration:none;cursor:pointer}
.commit-ref:hover,.commit-ref:focus-visible{border-color:var(--ink);outline:none}
.chip{display:inline-flex;align-items:center;gap:5px;white-space:nowrap;font-family:var(--mono);font-weight:500;font-size:11px;padding:2px 8px;border-radius:3px;border:0;background:var(--surface-2);color:var(--muted)}
.chip.good{background:color-mix(in srgb,var(--good) 16%,transparent);color:var(--good)}
.chip.warn{background:color-mix(in srgb,var(--warn) 16%,transparent);color:var(--warn)}
.chip.bad{background:color-mix(in srgb,var(--bad) 16%,transparent);color:var(--bad)}
.chip.off{background:none;color:var(--soft)}
.chip.busy::before{content:"";width:6px;height:6px;border-radius:50%;background:currentColor;flex:none;animation:chip-pulse 1s infinite}
@keyframes chip-pulse{50%{opacity:.25}}
@media (prefers-reduced-motion: reduce){.chip.busy::before{animation:none}}
.unlit,[disabled],[aria-disabled="true"]{opacity:.45;cursor:not-allowed}
/* Never pointer-events:none here: it takes the title with it, and the title
   is the reason. What must not fire is prevented where it is bound. */
.unlit,[aria-disabled="true"]{pointer-events:auto}
.nothing{font-family:var(--serif);font-style:italic;color:var(--muted)}
.fetch{display:flex;align-items:stretch;gap:8px}
.fetch>:first-child{flex:1;min-width:0;max-width:none}
/* The square's size is the field's height: 2.5em of the field's type, 13px — the reload of a .fetch had it, and every square has it now, whole pixels so the mark sits centred. */
.sq{display:inline-flex;align-items:center;justify-content:center;flex:none;font-size:13px;width:round(2.5em,1px);height:round(2.5em,1px);line-height:1;padding:0;border:1px solid var(--line);border-radius:2px;background:var(--surface-2);color:var(--muted);cursor:pointer;text-decoration:none;font-family:inherit}
.sq:hover,.sq:focus-visible{color:var(--ink);background:var(--surface)}
.sq svg{width:15px;height:15px;display:block;pointer-events:none}
.fetch>.sq{font-size:inherit}
/* Small: a line's height, 2em of 11px, with the mark a pixel smaller so it sits on whole pixels there too. */
.sq.small{font-size:11px;width:round(2em,1px);height:round(2em,1px)}
.sq.small svg{width:14px;height:14px}
.sq[aria-busy="true"]{color:var(--accent);cursor:progress}
.sq[aria-busy="true"] svg{animation:fetch-turn 1s linear infinite}
.sq[aria-disabled="true"],.sq:disabled{cursor:default}
@keyframes fetch-turn{to{transform:rotate(360deg)}}
@media (prefers-reduced-motion: reduce){.fetch>.go[aria-busy="true"] svg{animation:none}}
.sr{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap;border:0}
.fold{font:inherit;letter-spacing:inherit;text-transform:inherit;color:inherit;background:none;border:0;padding:0;margin:0;cursor:pointer;text-align:left;width:100%}
.fold::after{content:"▸";flex:none;width:.8em;margin-left:auto;color:var(--soft);font-family:var(--mono);font-size:max(1.25em,17px);line-height:1;letter-spacing:0;text-align:right}
.fold[aria-expanded="true"]::after{content:"▾"}
.fold:hover::after,.fold:focus-visible::after{color:var(--ink)}
input[type="checkbox"],input[type="radio"]{accent-color:var(--accent)}
::selection{background:var(--selection)}
@supports (appearance: base-select){
  select,select::picker(select){appearance:base-select}
  select::picker-icon{color:var(--muted);transition:transform .15s}
  select:open::picker-icon{transform:rotate(180deg)}
  select::picker(select){background:var(--surface);color:var(--ink);border:1px solid var(--line);border-radius:3px;
    box-shadow:var(--shadow);padding:4px;margin-top:3px;max-height:min(52vh,420px);overflow:auto;
    scrollbar-color:var(--scroll) transparent}
  select option{padding:5px 8px;border-radius:2px;background:none;color:var(--ink);font:inherit;display:flex;align-items:center;gap:8px}
  select option:hover{background:var(--accent-soft)}
  select option:focus{background:var(--accent-soft);outline:none}
  select option:checked{background:var(--surface-2)}
  select option::checkmark{content:"";width:0}
  /* The group's label is drawn by the browser off the optgroup itself —
     the customizable select puts a <legend> in the reach of CSS, but a
     <legend> inside an <optgroup> is markup no other browser parses, and
     the house does not write markup for one engine. So the label takes
     what the element can give it: the muted ink of every other label,
     and its options say their own font and colour rather than inherit
     these. */
  select optgroup{padding:2px 0 0;color:var(--muted)}
}
:root{scrollbar-color:var(--scroll) transparent}
/* .num — a measure in a column: cpu, memory, a size, a duration. Mono,
   because it is read off the machine; flush right, so that with the
   decimals fixed the points line up on their own; tabular digits and no
   wrapping. The two things this cannot do are the writer's: one unit
   per column and a fixed number of decimals, so that a value's *length*
   never changes between two readings — Docker's own three significant
   figures (`1.9MB`, `1.84MB`, `282.4MiB`) made every refresh of the
   stats redraw the columns — and, where a value is redrawn live, a
   reserved width in `ch` for the widest one the column can hold. */
.num{font-family:var(--mono);text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}
.stamp{display:inline-block;font-family:var(--cond);font-weight:700;letter-spacing:.14em;text-transform:uppercase;font-size:10.5px;color:var(--accent-ink);background:var(--accent);padding:3px 8px;border-radius:2px;transform:rotate(8deg);box-shadow:0 2px 4px rgba(0,0,0,.3)}
"""

# --- favicon.svg ---------------------------------------------------------------
# The tab's mark: the band's own lockup at 16 pixels — the workbench in
# board-ink on a full-bleed board plate. The plate is not decoration. The
# mark is fill="currentColor" (see console_live.ex, which inlines it so it
# takes the band's ink), and a favicon has no band to take ink from: left on
# transparent it renders black on a light tab strip and disappears on a dark
# one. The plate is what gives it its own ink, and the colour is the one
# thing that survives at 16 pixels, where DEW and the drawers are already
# noise and only the silhouette and the violet still say whose tab this is.
# Not gold: the accent has three uses and a tab is none of them.
#
# The mark comes in from the file it lives in rather than being pasted here,
# for the same reason the console reads it instead of holding a copy. The
# padding is 1/16 of the tile — measured at 16 px against 0, 2, 6 and 8:
# tighter and the bench's legs sit on the tile's edge as if cropped, wider
# and the drawing shrinks into a blur.
#
# favicon.ico beside it is the fallback for what does not take an SVG icon,
# rendered from this file once and committed, since it only changes when the
# mark does:
#     inkscape --export-type=png --export-filename=<n>.png --export-width=<n> \
#              --export-height=<n> console/priv/static/favicon.svg   # 16, 32, 48
#     magick 16.png 32.png 48.png console/priv/static/favicon.ico
MARK = os.path.join(ROOT, "console", "priv", "static", "images", "logo.svg")

# --- the sprite of marks ------------------------------------------------------
# One file per drawing under icons/, a 24-unit box in currentColor, the way
# a drawing is edited; one sprite in the console, the way a drawing is
# served: <svg><use href="/images/icons.svg#eye"/></svg> (ConsoleWeb.Square).
ICONS = os.path.join(HERE, "icons")

def icons_svg():
    symbols = []
    for name in sorted(os.listdir(ICONS)):
        if not name.endswith(".svg"): continue
        svg = open(os.path.join(ICONS, name)).read()
        box = re.search(r'viewBox="([^"]+)"', svg).group(1)
        inner = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S).group(1).strip()
        symbols.append(f'  <symbol id="{name[:-4]}" viewBox="{box}">{inner}</symbol>')
    return ('<!-- generated by assets/design/build.py from assets/design/icons/*.svg — edit those, not this -->\n'
            '<svg xmlns="http://www.w3.org/2000/svg">\n' + "\n".join(symbols) + "\n</svg>\n")

def favicon_svg(tile=64, pad=4):
    mark = open(MARK).read()
    box = re.search(r'viewBox="0 0 (\d+) (\d+)"', mark)
    side = max(int(box.group(1)), int(box.group(2)))
    inner = textwrap.dedent(re.search(r"<svg[^>]*>(.*)</svg>", mark, re.S).group(1)).strip("\n")
    scale = (tile - 2 * pad) / side
    return (f'<!-- generated by assets/design/build.py from assets/design/tokens.json and\n'
            f'     console/priv/static/images/logo.svg — edit those, not this -->\n'
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {tile} {tile}" '
            f'fill="{role("board-ink", "light")}">\n'
            f'  <rect width="{tile}" height="{tile}" fill="{role("board", "light")}"/>\n'
            f'  <g transform="translate({pad},{pad}) scale({scale:.8f})">\n'
            + "\n".join("    " + line for line in inner.splitlines()) + "\n  </g>\n</svg>\n")

# The console links tokens.css and components.css from its own static
# directory: the same two projections, written twice, and --check keeps
# the copies honest.
CONSOLE_CSS = os.path.join(ROOT, "console", "priv", "static", "assets", "css")
outputs = {
    os.path.join(GEN, "tokens.css"): tokens_css(),
    os.path.join(GEN, "components.css"): components_css(),
    os.path.join(CONSOLE_CSS, "tokens.css"): tokens_css(),
    os.path.join(CONSOLE_CSS, "components.css"): components_css(),
    os.path.join(GEN, "diagram-design.md"): "<!-- generated by assets/design/build.py from assets/design/tokens.json — edit the tokens, not this -->\n" + guide(),
    os.path.join(ROOT, "console", "priv", "static", "favicon.svg"): favicon_svg(),
    os.path.join(ROOT, "console", "priv", "static", "images", "icons.svg"): icons_svg(),
}
profiles = os.path.expanduser("~/.diagram-design/profiles")
installed = os.path.join(profiles, "workbench.md")
marker = os.path.join(ROOT, ".diagram-design")

stale = []
for path, content in outputs.items():
    if CHECK:
        if not os.path.isfile(path) or open(path).read() != content: stale.append(path)
    else:
        os.makedirs(os.path.dirname(path), exist_ok=True); open(path, "w").write(content)

body = guide()
if CHECK:
    if not os.path.isfile(installed) or re.sub(r"^<!--.*?-->\n", "", open(installed).read(), flags=re.S) != body: stale.append(installed)
    if not os.path.isfile(marker) or open(marker).read() != "profile: workbench\n": stale.append(marker)
else:
    os.makedirs(profiles, exist_ok=True)
    # Keep the current profile's created date when it has one.
    if os.path.isfile(installed):
        m = re.search(r"^created: (\S+)$", open(installed).read(), re.M)
        text = profile(body)
        if m: text = re.sub(r"^created: \S+$", f"created: {m.group(1)}", text, count=1, flags=re.M)
    else:
        text = profile(body)
    open(installed, "w").write(text)
    open(marker, "w").write("profile: workbench\n")
    # The skill's recovery copy of its pristine guide, if it is not there yet.
    default = os.path.join(profiles, "default.md")
    if not os.path.isfile(default):
        for cand in sorted(__import__("glob").glob(os.path.expanduser("~/.claude/plugins/cache/diagram-design/diagram-design/*/skills/diagram-design/references/style-guide.md"))):
            pristine = open(cand).read()
            if not pristine.startswith("<!-- diagram-design-profile") and "#f5f5f5" in pristine:
                today = datetime.date.today().isoformat()
                open(default, "w").write(f"<!-- diagram-design-profile\nname: Default\nslug: default\nsource-url: none\ncreated: {today}\nupdated: {today}\nnotes: Pristine shipped style guide\n-->\n" + pristine)
                break

if CHECK:
    if stale:
        print("stale:", *stale, sep="\n  "); sys.exit(1)
    print("design projections are current")
else:
    print("wrote", *outputs, installed, marker, sep="\n  ")
