#!/usr/bin/env python3
"""The house's design tokens, projected to whoever consumes them.

    ./assets/design/build.py            write every projection
    ./assets/design/build.py --check    exit 1 if any projection is stale

Reads tokens.json — the one source — and writes, marked as generated:

  generated/tokens.css          custom properties for the console (light on
                                :root, dark under prefers-color-scheme guarded
                                by :root:not([data-theme="light"]), and again
                                under :root[data-theme="dark"])
  generated/diagram-design.md   the diagram-design skill's style guide, with
                                the house's roles and type mapped onto its
                                semantic roles; also installed as the profile
                                ~/.diagram-design/profiles/workbench.md, which
                                the repository's .diagram-design marker names

Run from the repository root.
"""
import json, os, re, sys, datetime, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
GEN = os.path.join(HERE, "generated")
CHECK = "--check" in sys.argv
T = json.load(open(os.path.join(HERE, "tokens.json")))
PALETTE = {k: v["value"] for k, v in T["palette"].items()}

def resolve(v):
    return re.sub(r"\{([\w-]+)\}", lambda m: PALETTE[m.group(1)], v)

def role(name, mode):
    r = T["roles"][name]
    return resolve(r["value"] if "value" in r else r[mode])

def hex_to_rgb(h):
    h = h.lstrip("#"); return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))

def rgba(h, a):
    return "rgba(%d,%d,%d,%s)" % (*hex_to_rgb(h), a)

HEADER = "/* generated by assets/design/build.py from assets/design/tokens.json — edit the tokens, not this */\n"

# --- tokens.css ----------------------------------------------------------------
def css_block(mode, indent):
    lines = []
    for name, r in T["roles"].items():
        if "value" in r and mode == "dark":
            continue  # one value, both themes: written once on :root
        lines.append(f"{indent}--{name}:{role(name, mode)};")
    if mode == "light":
        for key, f in T["type"].items():
            lines.append(f'{indent}--{f["css"]}:"{f["family"]}",{f["fallback"]};')
    return "\n".join(lines)

def tokens_css():
    return (HEADER +
            ":root{\n" + css_block("light", "  ") + "\n}\n"
            "@media (prefers-color-scheme: dark){\n  :root:not([data-theme=\"light\"]){\n" + css_block("dark", "    ") + "\n  }\n}\n"
            ":root[data-theme=\"dark\"]{\n" + css_block("dark", "  ") + "\n}\n")

# --- the diagram skill's style guide -------------------------------------------
# The skill thinks in paper/ink/muted/soft/rule/accent/link; the house in
# ground/surface/ink/muted/line/accent. The mapping, with its reasons:
#   paper      <- ground     the page; the diagram sits on it
#   paper-2    <- surface-2  the framed variant's container
#   ink/muted/soft/link/accent <- the same roles
#   rule       <- line       hairlines; the skill's rule is ink at 12%, ours a hex
#   rule-solid <- muted at 45%
#   accent-tint<- accent at 10% (light) / 14% (dark), as accent-soft
#   title      <- text (Source Serif 4): the serif the backs are set in
#   node-name  <- display (Barlow Condensed): the band's lettering
#   sublabel/eyebrow/arrow-label <- code (IBM Plex Mono)
def guide():
    L = lambda n: role(n, "light"); D = lambda n: role(n, "dark")
    disp, text, code = T["type"]["display"]["family"], T["type"]["text"]["family"], T["type"]["code"]["family"]
    fonts = T["google-fonts"]
    return f"""# Style Guide

**The single source of truth for colors, typography, and tokens** of this
install — generated from the workbench's `assets/design/tokens.json` by
`assets/design/build.py`. Edit the tokens there and rebuild; never edit
this file.

The skin is the Dockerized Elixir Workbench's: a violet-tinted ground,
violet-black ink, the gold of the seal as the one accent, the band's
condensed lettering for names and the backs' serif for titles.

---

## Tokens

### Semantic roles

Every token is referred to by **semantic role**, not by its hex value. Type references (`type-*.md`) and SKILL.md say `accent`, not a hex.

| Role | Purpose | Default (light) | Default (dark) |
|---|---|---|---|
| `paper` | Page background, default node fill | `{L("ground")}` | `{D("ground")}` |
| `paper-2` | Diagram container bg, secondary fill | `{L("surface-2")}` | `{D("surface-2")}` |
| `ink` | Primary text, primary stroke | `{L("ink")}` | `{D("ink")}` |
| `muted` | Secondary text, default arrow stroke | `{L("muted")}` | `{D("muted")}` |
| `soft` | Sublabels, boundary labels | `{L("soft")}` | `{D("soft")}` |
| `rule` | Hairline borders | `{L("line")}` | `{D("line")}` |
| `rule-solid` | Stronger borders, baselines | `{rgba(L("muted"), 0.45)}` | `{rgba(D("muted"), 0.45)}` |
| `accent` | Focal / 1–2 max per diagram | `{L("accent")}` | `{D("accent")}` |
| `accent-tint` | Fill for accent-bordered boxes | `{L("accent-soft")}` | `{D("accent-soft")}` |
| `link` | HTTP/API calls, external arrows | `{L("link")}` | `{D("link")}` |

> **Brand palette source:** the workbench's palette — `violet {PALETTE["violet"]}` (the covers' board), `gold {PALETTE["gold"]}` (the seal; `{PALETTE["gold-deep"]}` on light ground), and the violet-tinted greys the console reads on. `board` (`{PALETTE["violet"]}`) is not a diagram role: it is the band and the covers, and a node painted in it would read as a box, not a component.

### Inversion rule (light → dark)

Any `rgba(29,20,36, X)` in light becomes `rgba(239,231,242, X)` in dark. Same opacities, RGB flipped. The accent brightens from the deep gold to the seal's gold on dark paper.

### Series palette (multi-series chart types only)

The workbench's service colours, which its logs already use to tell services apart; `accent` stays reserved for the focal series.

| Token | Light | Dark | Notes |
|---|---|---|---|
| `series-1` | `{role("svc-app","light")}` | `{role("svc-app","light")}` | the app |
| `series-2` | `{role("svc-database","light")}` | `{role("svc-database","light")}` | the database |
| `series-3` | `{role("svc-pgadmin","light")}` | `{role("svc-pgadmin","light")}` | pgAdmin |
| `series-4` | `{role("svc-balancer","light")}` | `{role("svc-balancer","light")}` | the balancer |
| `series-5` | `{role("svc-network","light")}` | `{role("svc-network","light")}` | the network container |

Fills sit at `0.18` opacity light, `0.22` dark; strokes use the full color. **Don't backfill these tokens to non-chart types.**

### Terminal skin (opt-in alternate)

The console's own terminal, for the terminal-window primitive (see [primitive-terminal.md](primitive-terminal.md)).

| Token | Hex | Purpose |
|---|---|---|
| `terminal-page` | `{D("ground")}` | Page background behind the window |
| `terminal-paper` | `{role("term","light")}` | Window body, node fill |
| `terminal-bar` | `{role("term-line","light")}` | Titlebar strip |
| `terminal-border` | `{role("term-line","light")}` | Window border, hairlines |
| `terminal-ink` | `{role("term-ink","light")}` | Primary text, primary stroke |
| `terminal-muted` | `{role("term-dim","light")}` | Secondary text, sublabels, ring stroke |
| `terminal-soft` | `{D("soft")}` | Tertiary — inactive dots, spokes |
| `terminal-accent` | `{D("accent")}` | The one accent — focal station, prompt sign, active dot |
| `terminal-accent-tint` | `{D("accent-soft")}` | Fill for accent-bordered boxes |

**1-accent rule still holds.**

---

## Typography

| Role | Family | Size | Weight | Usage |
|---|---|---|---|---|
| `title` | {text} | 1.75rem | 400 | Page H1 |
| `node-name` | {disp} | 13px | 600, tracked 0.04em | Human-readable labels |
| `sublabel` | {code} | 9px | 400 | Port, protocol, URL, field type |
| `eyebrow` | {code} | 7–8px | 500, tracked 0.18em, uppercase | Type tags, axis labels |
| `arrow-label` | {code} | 8px | 400, tracked 0.06em | Arrow annotations |
| `callout` | {text} *italic* | 14px | 400 | Editorial asides only |

### Font stack

```html
<link href="{fonts}" rel="stylesheet">
```

**Load-bearing rule:** Mono is for *technical* content (ports, commands, URLs, field types). Names go in {disp} — the band's lettering, so a node reads like a label on the machine. Page title is {text}. Italic {text} is reserved for annotation callouts (see [primitive-annotation.md](primitive-annotation.md)). **Never JetBrains Mono** as a blanket "dev" font.

---

## Stroke, radius, spacing

| Token | Value | Use |
|---|---|---|
| `stroke-thin` | `0.8` | Tag-box outlines, leaf nodes |
| `stroke-default` | `1` | Most strokes |
| `stroke-strong` | `1.2` | Emphasis strokes |
| `radius-sm` | `4` | Small tags |
| `radius-md` | `6` | Node boxes |
| `radius-lg` | `8` | Containers, rings |
| `grid` | `4` | Every coord, size, and gap is divisible by 4 (hard rule) |

---

## Node type → treatment

Semantic role combinations — reference these by name in type specs.

| Type | Fill | Stroke |
|---|---|---|
| `focal` (1–2 max) | `accent-tint` | `accent` |
| `backend` | `{L("surface")}` (surface; `{D("surface")}` dark) | `ink` |
| `store` | `ink @ 0.05` | `muted` |
| `external` | `ink @ 0.03` | `ink @ 0.30` |
| `input` | `muted @ 0.10` | `soft` |
| `optional` | `ink @ 0.02` | `ink @ 0.20` dashed `4,3` |
| `security` | `accent @ 0.05` | `accent @ 0.50` dashed `4,4` |

---

## Customizing the skin

This guide is a projection of `assets/design/tokens.json` in the workbench repository: change the tokens and run `./assets/design/build.py`, which rewrites this file and the installed profile.

### Constraints (don't break these)

- **Contrast**: `ink` must hit WCAG AA on `paper`. `muted` must hit AA on `paper` for 11px+ text.
- **One accent**: the seal's gold. Two accents erases the focal signal.
- **No rainbow palette**: the service colours are for series only.
- **Serif + condensed + mono**: three families, not more.
- **Dot pattern is optional, not default.**
- **Container is clean by default.**
"""

def profile(body):
    today = datetime.date.today().isoformat()
    return (f"<!-- diagram-design-profile\nname: {T['name']}\nslug: workbench\nsource-url: none\n"
            f"created: 2026-08-29\nupdated: {today}\nnotes: generated from assets/design/tokens.json by assets/design/build.py\n-->\n" + body)

# --- write or check --------------------------------------------------------------
outputs = {
    os.path.join(GEN, "tokens.css"): tokens_css(),
    os.path.join(GEN, "diagram-design.md"): "<!-- generated by assets/design/build.py from assets/design/tokens.json — edit the tokens, not this -->\n" + guide(),
}
profiles = os.path.expanduser("~/.diagram-design/profiles")
installed = os.path.join(profiles, "workbench.md")
marker = os.path.join(ROOT, ".diagram-design")

stale = []
for path, content in outputs.items():
    if CHECK:
        if not os.path.isfile(path) or open(path).read() != content: stale.append(path)
    else:
        os.makedirs(os.path.dirname(path), exist_ok=True); open(path, "w").write(content)

body = guide()
if CHECK:
    if not os.path.isfile(installed) or re.sub(r"^<!--.*?-->\n", "", open(installed).read(), flags=re.S) != body: stale.append(installed)
    if not os.path.isfile(marker) or open(marker).read() != "profile: workbench\n": stale.append(marker)
else:
    os.makedirs(profiles, exist_ok=True)
    # Keep the current profile's created date when it has one.
    if os.path.isfile(installed):
        m = re.search(r"^created: (\S+)$", open(installed).read(), re.M)
        text = profile(body)
        if m: text = re.sub(r"^created: \S+$", f"created: {m.group(1)}", text, count=1, flags=re.M)
    else:
        text = profile(body)
    open(installed, "w").write(text)
    open(marker, "w").write("profile: workbench\n")
    # The skill's recovery copy of its pristine guide, if it is not there yet.
    default = os.path.join(profiles, "default.md")
    if not os.path.isfile(default):
        for cand in sorted(__import__("glob").glob(os.path.expanduser("~/.claude/plugins/cache/diagram-design/diagram-design/*/skills/diagram-design/references/style-guide.md"))):
            pristine = open(cand).read()
            if not pristine.startswith("<!-- diagram-design-profile") and "#f5f5f5" in pristine:
                today = datetime.date.today().isoformat()
                open(default, "w").write(f"<!-- diagram-design-profile\nname: Default\nslug: default\nsource-url: none\ncreated: {today}\nupdated: {today}\nnotes: Pristine shipped style guide\n-->\n" + pristine)
                break

if CHECK:
    if stale:
        print("stale:", *stale, sep="\n  "); sys.exit(1)
    print("design projections are current")
else:
    print("wrote", *outputs, installed, marker, sep="\n  ")
