import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
public_port = System.get_env("CONSOLE_PUBLIC_PORT") || System.get_env("PORT") || "4000"

config :console, ConsoleWeb.Endpoint,
  # 0.0.0.0 inside the container, where the port has to be reachable
  # from the host; `./wb.sh console` publishes it on 127.0.0.1 only. The
  # console runs wb.sh with --yes over Docker's socket, and `delete`
  # wipes a workspace: the origin check stays on even in dev, so no
  # page the reader visits while the console is up can open its socket.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  # The port is part of the check: the project's pages are served on
  # the port beside this one (ConsoleWeb.Reports), the same host, and
  # "//localhost" alone lets them in. CONSOLE_PUBLIC_PORT is the port
  # the browser sees when Docker publishes 4000 on another.
  check_origin: ["//localhost:#{public_port}", "//127.0.0.1:#{public_port}"],
  code_reloader: true,
  # The shelf is read in this BEAM off the workbench's package, a path
  # dependency: reloaded with the console, or a cartridge edited while
  # the console is up keeps the options it was compiled with.
  reloadable_apps: [:console, :workbench_igniter],
  debug_errors: true,
  secret_key_base: "wxTY0splQ/Tx263CaVPTwythqPGkzx4CNjpsMrqwml5cth8XFB8xOTNHSmbuWVRz",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:console, ~w(--sourcemap=inline --watch)]}
  ]

# The project's docs and coverage report, on their own origin
# (ConsoleWeb.Reports): the port beside the console's, published on
# 127.0.0.1 like it.
config :console, :reports,
  ip: {0, 0, 0, 0},
  port: String.to_integer(System.get_env("REPORTS_PORT") || "4001")

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :console, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
