ARG        ELIXIR="%{elixir_version}"
ARG           OTP="%{erlang_version}"
ARG        DEBIAN="%{debian_version}"
ARG DEVELOP_IMAGE="hexpm/elixir:${ELIXIR}-erlang-${OTP}-debian-${DEBIAN}"
# ------------------------------------------------------------------------------
FROM ${DEVELOP_IMAGE} AS develop
# ------------------------------------------------------------------------------

# install build dependencies
RUN apt-get update -y && \
    apt-get install -y build-essential git inotify-tools && \
    apt-get clean && \
    rm -f /var/lib/apt/lists/*_*

# prepare build dir
WORKDIR /app

# install hex + rebar and Phoenix
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex phx_new --force

# Copies and makes excecutable the script to start the service.
COPY %{entrypoint} ./
RUN chmod +x %{entrypoint}
RUN sed -i -e 's/\r$//' %{entrypoint}
    
# Copies the script to generate mutation files.
COPY %{schemas} ./
RUN chmod +x %{schemas}
RUN sed -i -e 's/\r$//' %{schemas}

# ERROR: If any of these two script are saved with Windows (\r\n) will throw the
# following error:
#   exec ./entrypoint.sh: no such file or directory
# SOLUTION: The RUN seed lines solves it.

CMD ["./%{entrypoint}"]