ARG        ELIXIR="%{elixir_version}"
ARG           OTP="%{erlang_version}"
ARG        DEBIAN="%{debian_version}"
ARG DEVELOP_IMAGE="hexpm/elixir:${ELIXIR}-erlang-${OTP}-debian-${DEBIAN}"
# ------------------------------------------------------------------------------
FROM ${DEVELOP_IMAGE} AS develop
# ------------------------------------------------------------------------------

# install build dependencies
RUN apt-get update -y && \
    apt-get install -y build-essential git inotify-tools && \
    apt-get clean && \
    rm -f /var/lib/apt/lists/*_*

# prepare build dir
WORKDIR /app

# install hex + rebar and Phoenix
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex phx_new --force

# Copies the script to generate mutation files.
# Copies and makes excecutable the script to start the service.
COPY ./schemas.sh ./
COPY ./entrypoint.sh ./
RUN chmod +x schemas.sh
RUN chmod +x entrypoint.sh
# ERROR: If the script is saved with win (\r\n) will throw the following error:
#   exec ./entrypoint.sh: no such file or directory
# SOLUTION: These lines solves it.
RUN sed -i -e 's/\r$//' schemas.sh
RUN sed -i -e 's/\r$//' entrypoint.sh

CMD ["./entrypoint.sh"]