#!/bin/bash
# Elixir App image entrypoint script (Igniter edition)

# Prints service script name with arguments detail
if [ $# -gt 0 ]; then echo "[$HOSTNAME]$0($#): $@"; fi

# CONFIGURATION ----------------------------------------------------------------
  # Text formatting codes
  export C1="\x1B[38;5;1m"
  export B="\x1B[1m"
  export R="\x1B[0m"

# FUNCTIONS --------------------------------------------------------------------

  # If echo handles -e option, overrides the command
  if [ "$(echo -e)" == "" ]; then echo() { command echo -e "$@"; } fi

  # failure()
    # Prints error and spects input prompt for continue or cancel
  failure() {
    echo "🛑  ${B}${C1}Failure${R}"
    read -n 1 -p $'Should continue? [y/N] ' INPUT
    if [ "$INPUT" != "y" ]; then
      exit 1
    fi
    echo
  }
  
  # args_error <ERROR>
    # Prints a default messages for argument errors.
  args_error() {
    if   [ "$1" == "missing" ];  then echo "Missing arguments."
    elif [ "$1" == "too_many" ]; then echo "Too many arguments."
    elif [ "$1" == "invalid" ];  then echo "Invalid argument."
    elif [ "$1" != "" ];         then echo "$@"
    else echo "Argument error."; fi
    exit 1
  }

  # default_cmd()
    # Default command to initialize the server
  default_cmd() { mix phx.server; }

# SCRIPT -----------------------------------------------------------------------

  # Every branch of this entrypoint runs mix: it requires the dev
  # toolchain image (Dockerfile.local). Fail with a clear message when
  # the app service points at the production image (release only, no
  # Elixir) instead of a cryptic "mix: command not found".
  if ! command -v mix > /dev/null; then
    echo "🛑  ${B}${C1}Error${R} This entrypoint requires the dev toolchain image."
    echo "The app service seems to be running the production image: point the"
    echo "workspace's docker-compose.yml back to 'Dockerfile.local' and its"
    echo "':local' image. Production deployments use their own compose file,"
    echo "baked by 'up --env prod'."
    exit 1
  fi

  cd "src"
  
  if   [ "$1" == "new" ]; then
    shift
    if [ $# -ge 1 ]; then
      PROJECT_NAME=$1; shift

      { echo y; echo n; } | mix phx.new . --app $PROJECT_NAME --verbose $@

    elif [ $# -lt 2 ]; then args_error missing
    else args_error too_many; fi

  elif [ "$1" == "workbench_setup" ]; then
    shift

    mix deps.get && \
    mix workbench.setup "$@" --yes && \
    # New deps may conflict with versions pinned by the initial lock
    # (e.g. swoosh locks idna 7.x while hackney needs ~> 6.1): on
    # failure, re-resolve the whole lock.
    { mix deps.get || { mix deps.unlock --all && mix deps.get; }; } && \
    # --docker: the production Dockerfile and .dockerignore come from
    # Phoenix itself, with the stack versions detected from this
    # toolchain — no workbench-maintained template.
    mix phx.gen.release --docker && \
    mix release.init

  elif [ "$1" == "workbench_setup2" ]; then
    shift

    # The vanilla setup adds no dependency, so the lock generated by
    # phx.new minutes ago stays valid: no unlock/re-resolve dance here.
    mix deps.get && \
    mix workbench.setup2 "$@" --yes && \
    # --docker: the production Dockerfile and .dockerignore come from
    # Phoenix itself, with the stack versions detected from this
    # toolchain — no workbench-maintained template. 'mix release.init' is
    # NOT run here: its four rel/*.eex templates are pure customization
    # scaffolding (Mix carries the same defaults built in) and belong to
    # the clustering cartridge, which writes them with the exports a
    # distributed release actually needs.
    mix phx.gen.release --docker

  elif [ "$1" == "add" ]; then
    shift
    if [ $# -ge 1 ]; then
      FEATURE=$1; shift

      mix deps.get && \
      mix "workbench.install.$FEATURE" "$@" --yes && \
      mix deps.get

    else args_error missing; fi

  elif [ "$1" == "documentation" ]; then
    shift
    if [ $# -ge 2 ]; then
      EXDOC=$1; shift
      ECTO=$1; shift
      COVERALLS=$1; shift
      
      if [ $EXDOC == true ]; then
        if [ $ECTO == true ]; then
          mix db && \
          MIX_ENV="test" mix ecto.drop --force --force-drop && \
          MIX_ENV="test" mix ecto.create --quiet && \
          MIX_ENV="test" mix ecto.migrate --quiet
        fi && \
        if [ $COVERALLS == true ]; then mix cover || true; fi && \
        mix docs
      fi

    elif [ $# -lt 2 ]; then args_error missing
    else args_error too_many; fi

  elif [ "$1" == "setup" ]; then
    shift
    if [ $# -gt 0 ]; then
      export MIX_ENV="$1"

      # Outside dev, the seeds step boots the app from the mounted
      # source and Phoenix logs a "Could not warm up static assets"
      # error: digested assets only exist inside the release image.
      # Announce it as expected so the log explains itself.
      if [ "$MIX_ENV" != "dev" ]; then
        echo "ℹ️  ${B}Note${R} A 'Could not warm up static assets' error may" \
          "appear below. It is expected and harmless here: digested" \
          "production assets only exist inside the release image, and this" \
          "setup boots the app from the mounted source, where they are" \
          "never generated."
      fi

      mix ecto.drop --force --force-drop && \
      mix ecto.setup

    else args_error missing; fi
    
  else default_cmd; fi
