#!/bin/bash
# Elixir App image entrypoint script (Igniter edition)

# Prints service script name with arguments detail
if [ $# -gt 0 ]; then echo "[$HOSTNAME]$0($#): $@"; fi

# CONFIGURATION ----------------------------------------------------------------
  # Text formatting codes
  export C1="\x1B[38;5;1m"
  export B="\x1B[1m"
  export R="\x1B[0m"

# FUNCTIONS --------------------------------------------------------------------

  # If echo handles -e option, overrides the command
  if [ "$(echo -e)" == "" ]; then echo() { command echo -e "$@"; } fi

  # failure()
    # Prints error and spects input prompt for continue or cancel
  failure() {
    echo "🛑  ${B}${C1}Failure${R}"
    read -n 1 -p $'Should continue? [y/N] ' INPUT
    if [ "$INPUT" != "y" ]; then
      exit 1
    fi
    echo
  }
  
  # args_error <ERROR>
    # Prints a default messages for argument errors.
  args_error() {
    if   [ "$1" == "missing" ];  then echo "Missing arguments."
    elif [ "$1" == "too_many" ]; then echo "Too many arguments."
    elif [ "$1" == "invalid" ];  then echo "Invalid argument."
    elif [ "$1" != "" ];         then echo "$@"
    else echo "Argument error."; fi
    exit 1
  }

  # default_cmd()
    # Default command to initialize the server. `exec`, as the image's
    # CMD does: the BEAM takes PID 1 and with it the SIGTERM of a stop.
  default_cmd() { exec mix phx.server; }

# SCRIPT -----------------------------------------------------------------------

  # Every branch of this entrypoint runs mix: it requires the dev
  # toolchain image (Dockerfile.local). Fail with a clear message when
  # the app service points at the production image (release only, no
  # Elixir) instead of a cryptic "mix: command not found".
  if ! command -v mix > /dev/null; then
    echo "🛑  ${B}${C1}Error${R} This entrypoint requires the dev toolchain image."
    echo "The app service seems to be running the production image: point the"
    echo "workspace's docker-compose.yml back to 'Dockerfile.local' and its"
    echo "':local' image. Production deployments use their own compose file,"
    echo "baked by 'up --env prod'."
    exit 1
  fi

  cd "src"
  
  if   [ "$1" == "new" ]; then
    shift
    if [ $# -ge 1 ]; then
      PROJECT_NAME=$1; shift

      { echo y; echo n; } | mix phx.new . --app $PROJECT_NAME --verbose $@

    elif [ $# -lt 2 ]; then args_error missing
    else args_error too_many; fi

  elif [ "$1" == "workbench_setup" ]; then
    shift

    # The vanilla setup adds no dependency, so the lock generated by
    # phx.new minutes ago stays valid: no unlock/re-resolve dance here.
    mix deps.get && \
    mix workbench.setup "$@" --yes && \
    # --docker: the production Dockerfile and .dockerignore come from
    # Phoenix itself, with the stack versions detected from this
    # toolchain — no workbench-maintained template. 'mix release.init' is
    # NOT run here: its four rel/*.eex templates are pure customization
    # scaffolding (Mix carries the same defaults built in) and belong to
    # the clustering cartridge, which writes them with the exports a
    # distributed release actually needs.
    mix phx.gen.release --docker

  elif [ "$1" == "expand" ]; then
    shift
    if [ $# -ge 1 ]; then

      # The planning half of 'add': prints one 'plan> NAME [ARGS]' line
      # per install to run — a collection expands to its missing
      # members, a plain cartridge to itself. The caller filters by the
      # prefix; everything else is mix noise. Same compile-first dance
      # as 'add', so the manifest that answers is the current one.
      mix deps.get > /dev/null && \
      mix deps.compile workbench_igniter --force > /dev/null && \
      mix workbench.expand "$@"

    else args_error missing; fi

  elif [ "$1" == "add" ]; then
    shift
    if [ $# -ge 1 ]; then
      FEATURE=$1; shift

      # The igniter package is a path dependency on the mounted
      # workbench: compile it first, so an installer that changed since
      # the last run is the one that runs (Mix does not always notice).
      mix deps.get && \
      mix deps.compile workbench_igniter --force > /dev/null && \
      mix "workbench.install.$FEATURE" "$@" --yes && \
      mix deps.get

    else args_error missing; fi

  else default_cmd; fi
